import type { TFunction } from "i18next";

import type {
  ConfirmationCopy,
  PaymentFormCopy,
  PaymentReversalFormCopy,
  ReceivableFormCopy,
  ReceivableReviewCopy,
  ReceivablesCopy,
  VoidReceivableFormCopy,
} from "../receivables/types";
import type { CustomerFormCopy, CustomersCopy } from "./types";

export function buildCustomersCopy(t: TFunction) {
  const common = {
    back: t("relationships.common.back"),
    cancel: t("common.cancel"),
    clearValue: t("relationships.common.clearValue"),
    loading: t("relationships.common.loading"),
    noBusinessDescription: t("relationships.common.noBusinessDescription"),
    noBusinessTitle: t("relationships.common.noBusinessTitle"),
    notProvided: t("relationships.common.notProvided"),
    retry: t("common.retry"),
    unavailableDescription: t("relationships.common.unavailableDescription"),
    unavailableTitle: t("relationships.common.unavailableTitle"),
  };

  const access = {
    deniedDescription: t("relationships.access.deniedDescription"),
    deniedTitle: t("relationships.access.deniedTitle"),
    offlineDescription: t("remote.offlineDescription"),
    offlineTitle: t("relationships.access.offlineTitle"),
    stale: t("remote.staleMutation"),
  };

  const customersList: CustomersCopy = {
    active: t("customers.list.active"),
    all: t("customers.list.all"),
    archive: t("customers.list.archive"),
    archived: t("customers.list.archived"),
    archivedDescription: t("customers.list.archivedDescription"),
    back: t("customers.list.back"),
    balance: t("customers.list.balance"),
    contact: t("customers.list.contact"),
    create: t("customers.list.create"),
    deniedDescription: t("customers.list.deniedDescription"),
    deniedTitle: t("customers.list.deniedTitle"),
    description: t("customers.list.description"),
    email: t("customers.list.email"),
    emptyAction: t("customers.list.emptyAction"),
    emptyDescription: t("customers.list.emptyDescription"),
    emptyTitle: t("customers.list.emptyTitle"),
    errorDescription: t("customers.list.errorDescription"),
    errorTitle: t("customers.list.errorTitle"),
    filterLabel: t("customers.list.filterLabel"),
    loadMore: t("customers.list.loadMore"),
    loading: t("customers.list.loading"),
    name: t("customers.list.name"),
    newReceivable: t("customers.list.newReceivable"),
    noContact: t("customers.list.noContact"),
    noReceivables: t("customers.list.noReceivables"),
    notes: t("customers.list.notes"),
    offlineDescription: access.offlineDescription,
    offlineTitle: t("customers.list.offlineTitle"),
    openReceivables: t("customers.list.openReceivables"),
    overdue: t("customers.list.overdue"),
    phone: t("customers.list.phone"),
    receivableHistory: t("customers.list.receivableHistory"),
    retry: common.retry,
    searchEmptyDescription: t("customers.list.searchEmptyDescription"),
    searchEmptyTitle: t("customers.list.searchEmptyTitle"),
    searchLabel: t("customers.list.searchLabel"),
    searchPlaceholder: t("customers.list.searchPlaceholder"),
    stale: t("remote.stale"),
    title: t("customers.list.title"),
    unavailableDescription: t("customers.list.unavailableDescription"),
    unavailableTitle: t("customers.list.unavailableTitle"),
    update: t("customers.list.update"),
  };

  const customerForm: CustomerFormCopy = {
    cancel: common.cancel,
    confirmArchive: t("customers.form.confirmArchive"),
    email: t("customers.form.email"),
    emailPlaceholder: t("customers.form.emailPlaceholder"),
    name: t("customers.form.name"),
    namePlaceholder: t("customers.form.namePlaceholder"),
    notes: t("customers.form.notes"),
    notesPlaceholder: t("customers.form.notesPlaceholder"),
    phone: t("customers.form.phone"),
    phonePlaceholder: t("customers.form.phonePlaceholder"),
    retrySameConfirmation: t("common.retrySameConfirmation"),
    save: t("customers.form.save"),
    uncertainTitle: t("common.uncertainTitle"),
  };

  const receivablesList: ReceivablesCopy = {
    all: t("receivables.list.all"),
    applyPayment: t("receivables.list.applyPayment"),
    back: t("receivables.list.back"),
    cashAccount: t("receivables.list.cashAccount"),
    cashAccountLoading: t("receivables.list.cashAccountLoading"),
    cashAccountUnavailable: t("receivables.list.cashAccountUnavailable"),
    charge: t("receivables.list.charge"),
    confirmed: t("receivables.list.confirmed"),
    customerLoading: t("receivables.list.customerLoading"),
    customerUnavailable: t("receivables.list.customerUnavailable"),
    deniedDescription: t("receivables.list.deniedDescription"),
    deniedTitle: t("receivables.list.deniedTitle"),
    description: t("receivables.list.description"),
    dueDate: t("receivables.list.dueDate"),
    emptyAction: t("receivables.list.emptyAction"),
    emptyDescription: t("receivables.list.emptyDescription"),
    emptyTitle: t("receivables.list.emptyTitle"),
    errorDescription: t("receivables.list.errorDescription"),
    errorTitle: t("receivables.list.errorTitle"),
    filterLabel: t("receivables.list.filterLabel"),
    loadMore: t("receivables.list.loadMore"),
    loading: t("receivables.list.loading"),
    noDueDate: t("receivables.list.noDueDate"),
    noPayments: t("receivables.list.noPayments"),
    offlineDescription: access.offlineDescription,
    offlineTitle: t("receivables.list.offlineTitle"),
    open: t("receivables.list.open"),
    openCount: t("receivables.list.openCount"),
    originalAmount: t("receivables.list.originalAmount"),
    outstanding: t("receivables.list.outstanding"),
    overdue: t("receivables.list.overdue"),
    overdueCount: t("receivables.list.overdueCount"),
    paid: t("receivables.list.paid"),
    paymentHistory: t("receivables.list.paymentHistory"),
    paymentsUnavailableDescription: t("receivables.list.paymentsUnavailableDescription"),
    paymentsUnavailableTitle: t("receivables.list.paymentsUnavailableTitle"),
    postedDate: t("receivables.list.postedDate"),
    retry: common.retry,
    reverse: t("receivables.list.reverse"),
    reversedPayment: t("receivables.list.reversedPayment"),
    stale: t("remote.stale"),
    title: t("receivables.list.title"),
    unavailableDescription: t("receivables.list.unavailableDescription"),
    unavailableTitle: t("receivables.list.unavailableTitle"),
    void: t("receivables.list.void"),
    voided: t("receivables.list.voided"),
  };

  const confirmation: ConfirmationCopy = {
    cancel: t("receivables.review.cancel"),
    confirm: t("common.confirm"),
    confirming: t("receivables.review.confirming"),
    errorTitle: t("receivables.review.errorTitle"),
    retrySameConfirmation: t("common.retrySameConfirmation"),
    reviewTitle: t("receivables.review.reviewTitle"),
    uncertainDescription: t("receivables.review.uncertainDescription"),
    uncertainTitle: t("common.uncertainTitle"),
  };

  const review: ReceivableReviewCopy = {
    ...confirmation,
    amount: t("receivables.review.amount"),
    cashAccount: t("receivables.review.cashAccount"),
    customer: t("receivables.review.customer"),
    description: t("receivables.review.description"),
    dueDate: t("receivables.review.dueDate"),
    noDueDate: t("receivables.review.noDueDate"),
    occurrence: t("receivables.review.occurrence"),
    originalPayment: t("receivables.review.originalPayment"),
    postedDate: t("receivables.review.postedDate"),
    reason: t("receivables.review.reason"),
    reference: t("receivables.review.reference"),
  };

  const receivableForm: ReceivableFormCopy = {
    amount: t("receivables.form.amount"),
    amountPlaceholder: t("receivables.form.amountPlaceholder"),
    cancel: common.cancel,
    chooseCustomer: t("receivables.form.chooseCustomer"),
    customer: t("receivables.form.customer"),
    datePlaceholder: t("receivables.form.datePlaceholder"),
    description: t("receivables.form.description"),
    descriptionPlaceholder: t("receivables.form.descriptionPlaceholder"),
    dueDate: t("receivables.form.dueDate"),
    optional: t("receivables.form.optional"),
    postedDate: t("receivables.form.postedDate"),
    review: t("receivables.form.review"),
  };

  const paymentForm: PaymentFormCopy = {
    amount: t("receivables.paymentForm.amount"),
    amountPlaceholder: t("receivables.paymentForm.amountPlaceholder"),
    cancel: common.cancel,
    cashAccount: t("receivables.paymentForm.cashAccount"),
    chooseCashAccount: t("receivables.paymentForm.chooseCashAccount"),
    date: t("receivables.paymentForm.date"),
    datePlaceholder: t("receivables.paymentForm.datePlaceholder"),
    optional: t("receivables.paymentForm.optional"),
    reference: t("receivables.paymentForm.reference"),
    referencePlaceholder: t("receivables.paymentForm.referencePlaceholder"),
    review: t("receivables.paymentForm.review"),
    time: t("receivables.paymentForm.time"),
    timePlaceholder: t("receivables.paymentForm.timePlaceholder"),
  };

  const reversalForm: PaymentReversalFormCopy = {
    cancel: common.cancel,
    date: t("receivables.reversalForm.date"),
    datePlaceholder: t("receivables.reversalForm.datePlaceholder"),
    optional: t("receivables.reversalForm.optional"),
    reference: t("receivables.reversalForm.reference"),
    referencePlaceholder: t("receivables.reversalForm.referencePlaceholder"),
    review: t("receivables.reversalForm.review"),
    time: t("receivables.reversalForm.time"),
    timePlaceholder: t("receivables.reversalForm.timePlaceholder"),
  };

  const voidForm: VoidReceivableFormCopy = {
    cancel: common.cancel,
    reason: t("receivables.voidForm.reason"),
    reasonPlaceholder: t("receivables.voidForm.reasonPlaceholder"),
    review: t("receivables.voidForm.review"),
  };

  return {
    access,
    common,
    customers: {
      archive: {
        alreadyArchived: t("customers.archive.alreadyArchived"),
        description: t("customers.archive.description"),
        title: t("customers.archive.title"),
      },
      editor: {
        confirmCreate: t("customers.editor.confirmCreate"),
        confirmEdit: t("customers.editor.confirmEdit"),
        confirmedDescription: t("customers.editor.confirmedDescription"),
        createDescription: t("customers.editor.createDescription"),
        createTitle: t("customers.editor.createTitle"),
        editDescription: t("customers.editor.editDescription"),
        editTitle: t("customers.editor.editTitle"),
        noChanges: t("customers.editor.noChanges"),
        reviewCreateTitle: t("customers.editor.reviewCreateTitle"),
        reviewEditTitle: t("customers.editor.reviewEditTitle"),
      },
      form: customerForm,
      list: customersList,
      validation: {
        email: t("customers.validation.email"),
        name: t("customers.validation.name"),
        notes: t("customers.validation.notes"),
        phone: t("customers.validation.phone"),
      },
    },
    receivables: {
      form: receivableForm,
      list: receivablesList,
      paymentForm,
      picker: {
        activeAccountsDescription: t("receivables.picker.activeAccountsDescription"),
        activeAccountsTitle: t("receivables.picker.activeAccountsTitle"),
        activeCustomersDescription: t("receivables.picker.activeCustomersDescription"),
        activeCustomersTitle: t("receivables.picker.activeCustomersTitle"),
        loadMoreAccounts: t("receivables.picker.loadMoreAccounts"),
        noAccounts: t("receivables.picker.noAccounts"),
        noCustomers: t("receivables.picker.noCustomers"),
        select: t("receivables.picker.select"),
      },
      reversalForm,
      review,
      route: {
        actionUnavailableDescription: t("receivables.route.actionUnavailableDescription"),
        actionUnavailableTitle: t("receivables.route.actionUnavailableTitle"),
        newDescription: t("receivables.route.newDescription"),
        newTitle: t("receivables.route.newTitle"),
        paymentDescription: t("receivables.route.paymentDescription"),
        paymentTitle: t("receivables.route.paymentTitle"),
        reversalDescription: t("receivables.route.reversalDescription"),
        reversalTitle: t("receivables.route.reversalTitle"),
        voidDescription: t("receivables.route.voidDescription"),
        voidTitle: t("receivables.route.voidTitle"),
      },
      validation: {
        amount: t("receivables.validation.amount"),
        cashAccount: t("receivables.validation.cashAccount"),
        customer: t("receivables.validation.customer"),
        date: t("receivables.validation.date"),
        description: t("receivables.validation.description"),
        dueDate: t("receivables.validation.dueDate"),
        overpayment: t("receivables.validation.overpayment"),
        reason: t("receivables.validation.reason"),
        reference: t("receivables.validation.reference"),
        time: t("receivables.validation.time"),
      },
      voidForm,
    },
  };
}

export type CustomersReceivablesCopy = ReturnType<typeof buildCustomersCopy>;
