import { ApiClientError } from "@/lib/api-error";

export const customersReceivablesCopy = {
  common: {
    back: "Volver",
    cancel: "Cancelar",
    loading: "Cargando información…",
    noBusinessTitle: "Selecciona un negocio",
    noBusinessDescription:
      "Necesitas un negocio activo antes de administrar clientes y cuentas por cobrar.",
    notProvided: "No indicado",
    clearValue: "Eliminar dato guardado",
    retry: "Intentar de nuevo",
    unavailableTitle: "No pudimos cargar esta información",
    unavailableDescription:
      "Revisa tu conexión e inténtalo otra vez. No mostramos datos estimados cuando falla la consulta.",
  },
  access: {
    deniedTitle: "No tienes acceso a esta sección",
    deniedDescription:
      "Tu acceso actual no permite consultar ni administrar clientes y cuentas por cobrar.",
    stale:
      "Mostramos la última información disponible. No puedes confirmar cambios hasta verificar de nuevo tu acceso y los datos.",
    offlineTitle: "Sin conexión",
    offlineDescription:
      "Conéctate a internet para consultar clientes y cuentas por cobrar. Esta sección no inventa datos sin conexión.",
  },
  customers: {
    list: {
      active: "Activos",
      all: "Todos",
      archive: "Archivar",
      archived: "Archivado",
      archivedDescription:
        "Este cliente está archivado. Su historial sigue disponible, pero no puede recibir cargos nuevos.",
      back: "Volver a clientes",
      balance: "Saldo pendiente",
      contact: "Abrir detalle del cliente",
      create: "Nuevo cliente",
      deniedDescription:
        "Tu acceso actual no permite consultar la información privada de clientes.",
      deniedTitle: "Acceso a clientes denegado",
      description: "Consulta contactos, saldos y el historial real de cada cliente.",
      email: "Correo electrónico",
      emptyAction: "Crear el primer cliente",
      emptyDescription: "Aún no hay clientes con este estado.",
      emptyTitle: "No hay clientes",
      errorDescription:
        "No pudimos consultar los clientes. Inténtalo de nuevo; una falla no se presenta como una lista vacía.",
      errorTitle: "Clientes no disponibles",
      filterLabel: "Estado del cliente",
      loadMore: "Cargar más clientes",
      loading: "Cargando clientes…",
      name: "Nombre",
      newReceivable: "Registrar cuenta por cobrar",
      noContact: "Sin datos de contacto",
      noReceivables: "Este cliente todavía no tiene cuentas por cobrar.",
      notes: "Notas privadas",
      offlineDescription:
        "Conéctate a internet para consultar los clientes. No mostramos una lista vacía como reemplazo.",
      offlineTitle: "Clientes sin conexión",
      openReceivables: "Cuentas abiertas",
      overdue: "Vencido",
      phone: "Teléfono",
      receivableHistory: "Historial de cuentas por cobrar",
      retry: "Intentar de nuevo",
      searchEmptyDescription: "Prueba otro nombre, teléfono o correo electrónico.",
      searchEmptyTitle: "No encontramos coincidencias",
      searchLabel: "Buscar clientes",
      searchPlaceholder: "Nombre, teléfono o correo",
      stale:
        "Mostramos la última información disponible. Verifica la conexión antes de tomar una decisión.",
      title: "Clientes",
      unavailableDescription:
        "El cliente no existe o no está disponible dentro del negocio activo.",
      unavailableTitle: "Cliente no disponible",
      update: "Editar",
    },
    form: {
      cancel: "Cancelar",
      confirmArchive: "Confirmar archivo",
      email: "Correo electrónico (opcional)",
      emailPlaceholder: "nombre@ejemplo.com",
      name: "Nombre",
      namePlaceholder: "Nombre del cliente",
      notes: "Notas privadas (opcional)",
      notesPlaceholder: "Información útil para atender a este cliente",
      phone: "Teléfono (opcional)",
      phonePlaceholder: "Número de contacto",
      retrySameRequest: "Reintentar la misma solicitud",
      save: "Revisar",
      uncertainTitle: "No sabemos si el cambio fue confirmado",
    },
    editor: {
      createTitle: "Nuevo cliente",
      createDescription:
        "Agrega solo la información de contacto que necesitas. Podrás revisarla antes de guardar.",
      editTitle: "Editar cliente",
      editDescription: "Revisa exactamente qué datos cambiarán antes de confirmar.",
      reviewCreateTitle: "Revisa el nuevo cliente",
      reviewEditTitle: "Revisa los cambios del cliente",
      confirmCreate: "Crear cliente",
      confirmEdit: "Guardar cambios",
      confirmedDescription: "El servidor confirmó el registro del cliente.",
      noChanges: "Cambia al menos un dato antes de continuar.",
    },
    archive: {
      title: "Archivar cliente",
      description:
        "El cliente dejará de aceptar cambios y cargos nuevos. Su contacto e historial financiero se conservarán.",
      alreadyArchived: "Este cliente ya está archivado.",
    },
    validation: {
      email: "Escribe un correo electrónico válido.",
      name: "Escribe un nombre de 1 a 120 caracteres.",
      notes: "Las notas pueden tener hasta 1,000 caracteres.",
      phone: "El teléfono puede tener hasta 40 caracteres.",
    },
  },
  receivables: {
    list: {
      all: "Todas",
      applyPayment: "Registrar pago",
      back: "Volver a cuentas por cobrar",
      cashAccount: "Cuenta de efectivo",
      cashAccountLoading: "Cargando cuenta…",
      cashAccountUnavailable: "Cuenta no disponible",
      charge: "Nueva cuenta por cobrar",
      confirmed: "Confirmado",
      customerLoading: "Cargando cliente…",
      customerUnavailable: "Cliente no disponible",
      deniedDescription: "Tu acceso actual no permite consultar cuentas por cobrar ni sus pagos.",
      deniedTitle: "Acceso a cuentas por cobrar denegado",
      description:
        "Consulta saldos abiertos y vencidos calculados desde cargos y pagos confirmados.",
      dueDate: "Fecha de vencimiento",
      emptyAction: "Registrar la primera cuenta",
      emptyDescription: "No hay cuentas por cobrar que coincidan con este filtro.",
      emptyTitle: "No hay cuentas por cobrar",
      errorDescription:
        "No pudimos consultar los saldos. Inténtalo otra vez; una falla no se convierte en cero.",
      errorTitle: "Cuentas por cobrar no disponibles",
      filterLabel: "Estado de la cuenta por cobrar",
      loadMore: "Cargar más cuentas",
      loading: "Cargando cuentas por cobrar…",
      noDueDate: "Sin fecha de vencimiento",
      noPayments: "Todavía no hay pagos ni reversiones confirmados.",
      offlineDescription:
        "Conéctate a internet para consultar los saldos. Esta pantalla no presenta ceros sin verificar.",
      offlineTitle: "Cuentas por cobrar sin conexión",
      open: "Abierta",
      openCount: "Cuentas abiertas",
      originalAmount: "Monto original",
      outstanding: "Saldo pendiente",
      overdue: "Vencida",
      overdueCount: "Cuentas vencidas",
      paid: "Pagada",
      paymentHistory: "Historial de pagos",
      paymentsUnavailableTitle: "Pagos temporalmente deshabilitados",
      paymentsUnavailableDescription:
        "Pisto habilitará pagos y reversiones cuando cada operación pueda actualizar la cuenta de efectivo de forma atómica. Los cargos y anulaciones siguen disponibles.",
      postedDate: "Fecha del cargo",
      retry: "Intentar de nuevo",
      reverse: "Revertir pago",
      reversedPayment: "Reversión de pago",
      stale:
        "Mostramos la última información disponible. No confirmes cambios hasta actualizar los datos.",
      title: "Cuentas por cobrar",
      unavailableDescription:
        "La cuenta por cobrar no existe o no está disponible dentro del negocio activo.",
      unavailableTitle: "Cuenta por cobrar no disponible",
      void: "Anular",
      voided: "Anulada",
    },
    form: {
      amount: "Monto",
      amountPlaceholder: "0.00",
      cancel: "Cancelar",
      chooseCustomer: "Seleccionar un cliente activo",
      customer: "Cliente",
      description: "Descripción",
      descriptionPlaceholder: "Qué debe el cliente",
      dueDate: "Fecha de vencimiento",
      optional: "opcional",
      postedDate: "Fecha del cargo",
      datePlaceholder: "AAAA-MM-DD",
      review: "Revisar cargo",
    },
    paymentForm: {
      amount: "Monto del pago",
      amountPlaceholder: "0.00",
      cancel: "Cancelar",
      cashAccount: "Cuenta que recibe el dinero",
      chooseCashAccount: "Seleccionar una cuenta activa",
      date: "Fecha local",
      datePlaceholder: "AAAA-MM-DD",
      optional: "opcional",
      reference: "Referencia",
      referencePlaceholder: "Comprobante o nota breve",
      review: "Revisar pago",
      time: "Hora local",
      timePlaceholder: "HH:MM",
    },
    reversalForm: {
      cancel: "Cancelar",
      date: "Fecha local de la reversión",
      datePlaceholder: "AAAA-MM-DD",
      optional: "opcional",
      reference: "Referencia",
      referencePlaceholder: "Motivo o comprobante",
      review: "Revisar reversión",
      time: "Hora local",
      timePlaceholder: "HH:MM",
    },
    voidForm: {
      cancel: "Cancelar",
      reason: "Motivo de la anulación",
      reasonPlaceholder: "Explica por qué se anula este cargo",
      review: "Revisar anulación",
    },
    review: {
      amount: "Monto",
      cancel: "Editar",
      cashAccount: "Cuenta de efectivo",
      confirm: "Confirmar",
      confirming: "Confirmando…",
      customer: "Cliente",
      description: "Descripción",
      dueDate: "Vencimiento",
      errorTitle: "No se pudo confirmar",
      noDueDate: "Sin fecha de vencimiento",
      occurrence: "Fecha y hora local",
      originalPayment: "Pago original",
      postedDate: "Fecha del cargo",
      reason: "Motivo",
      reference: "Referencia",
      retrySameCommand: "Reintentar exactamente lo mismo",
      reviewTitle: "Revisa antes de confirmar",
      uncertainDescription:
        "No edites los datos ni generes otra solicitud. Reintenta exactamente este comando para conocer el resultado sin duplicarlo.",
      uncertainTitle: "El resultado es incierto",
    },
    picker: {
      activeCustomersTitle: "Selecciona un cliente activo",
      activeCustomersDescription: "Busca y elige el cliente que recibirá este cargo.",
      activeAccountsTitle: "Selecciona la cuenta que recibió el dinero",
      activeAccountsDescription:
        "Solo puedes elegir una cuenta de efectivo activa obtenida del servidor.",
      loadMoreAccounts: "Cargar más cuentas",
      noAccounts: "No hay cuentas de efectivo activas disponibles.",
      noCustomers: "No hay clientes activos que coincidan con la búsqueda.",
      select: "Seleccionar",
    },
    validation: {
      amount: "Escribe un monto positivo con la precisión de la moneda del negocio.",
      cashAccount: "Selecciona una cuenta de efectivo activa.",
      customer: "Selecciona un cliente activo.",
      date: "Escribe una fecha válida con formato AAAA-MM-DD.",
      description: "Escribe una descripción de 1 a 240 caracteres.",
      dueDate: "La fecha de vencimiento no puede ser anterior a la fecha del cargo.",
      overpayment: "El pago no puede superar el saldo pendiente confirmado.",
      reference: "La referencia puede tener hasta 120 caracteres.",
      reason: "Escribe un motivo de 1 a 240 caracteres.",
      time: "Escribe una hora válida con formato HH:MM.",
    },
    route: {
      newTitle: "Nueva cuenta por cobrar",
      newDescription:
        "Registra lo que un cliente debe y revisa el cargo exacto antes de confirmar.",
      paymentTitle: "Registrar pago",
      paymentDescription:
        "Elige la cuenta real que recibió el dinero y revisa el movimiento antes de confirmar.",
      reversalTitle: "Revertir pago",
      reversalDescription:
        "La reversión conservará el pago original y registrará una corrección por el mismo monto y cuenta.",
      voidTitle: "Anular cuenta por cobrar",
      voidDescription:
        "La anulación conserva el historial y solo puede confirmarse cuando el saldo pagado neto es cero.",
      actionUnavailableTitle: "Esta acción no está disponible",
      actionUnavailableDescription:
        "El estado actual del cliente, cargo o pago ya no permite confirmar esta operación.",
    },
  },
} as const;

export function capabilityErrorMessage(error: unknown, fallback: string): string {
  if (!(error instanceof ApiClientError)) return fallback;
  if (error.status === 0) return "No pudimos comunicarnos con el servidor.";
  const messages: Partial<Record<ApiClientError["code"], string>> = {
    BUSINESS_REQUIRED: "Selecciona un negocio activo antes de continuar.",
    CONFLICT:
      "Los datos cambiaron y esta operación ya no es válida. Actualiza e inténtalo de nuevo.",
    FORBIDDEN: "Tu acceso actual no permite confirmar esta operación.",
    IDEMPOTENCY_CONFLICT:
      "Esta clave ya fue usada con datos diferentes. Vuelve a revisar para crear una solicitud nueva.",
    NOT_FOUND: "El registro ya no está disponible dentro del negocio activo.",
    UNAUTHORIZED: "Tu sesión venció. Inicia sesión de nuevo.",
    VALIDATION_ERROR: "Revisa los datos. El servidor rechazó esta solicitud.",
  };
  return messages[error.code] ?? fallback;
}
