#!/usr/bin/env bun

import { randomBytes } from "node:crypto";
import { mkdir, open, readFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";

const PROJECT_ROOT = resolve(import.meta.dir, "..");
const MINIMUM_BUN_VERSION = "1.4.0";
const MINIMUM_NODE_VERSION = "24.19.0";
const MAXIMUM_NODE_VERSION = "25.0.0";
const EXPO_MINIMUM_NODE_VERSION = "22.13.0";

const SERVER_ENV_FALLBACK = `# Local Pisto Stack configuration.
# Generated by scripts/pisto.ts. Do not commit this file.
NODE_ENV=development
API_HOST=0.0.0.0
API_PORT=3001
API_REQUEST_BODY_LIMIT_BYTES=1048576

POSTGRES_USER=pisto
POSTGRES_PASSWORD=pisto_local_only
POSTGRES_DB=pisto
POSTGRES_PORT=5432
DATABASE_URL=postgresql://pisto:pisto_local_only@localhost:5432/pisto
DATABASE_MAX_CONNECTIONS=10
DATABASE_CONNECT_TIMEOUT_SECONDS=10
DATABASE_IDLE_TIMEOUT_SECONDS=20
DATABASE_SSL=disable

BETTER_AUTH_SECRET=__GENERATED_BETTER_AUTH_SECRET__
BETTER_AUTH_SECRETS=
BETTER_AUTH_URL=http://localhost:3001
CORS_ORIGINS=http://localhost:8081,http://localhost:19006
TRUSTED_ORIGINS=http://localhost:8081,http://localhost:19006,pisto://
EXPO_SCHEME=pisto
AUTH_EMAIL_PASSWORD_ENABLED=true
AUTH_TRUSTED_PROXY_HEADERS=false

# Polar is web billing only. Leave disabled until sandbox credentials are configured.
BILLING_ENABLED=false
POLAR_ACCESS_TOKEN=
POLAR_WEBHOOK_SECRET=
POLAR_SERVER=sandbox
POLAR_PRODUCTS_JSON=
POLAR_SUCCESS_URL=http://localhost:8081/billing/success
POLAR_RETURN_URL=http://localhost:8081/billing
POLAR_THEME=light

# RevenueCat is the native store-notification source. Keep disabled until configured.
REVENUECAT_ENABLED=false
REVENUECAT_WEBHOOK_AUTHORIZATION=
REVENUECAT_WEBHOOK_SIGNING_SECRET=
REVENUECAT_SIGNATURE_TOLERANCE_SECONDS=300
REVENUECAT_ENTITLEMENT_MAP_JSON=
`;

const APP_ENV_FALLBACK = `# Values prefixed with EXPO_PUBLIC_ are bundled into the client.
# Never place credentials or server-side secrets in this file.
EXPO_PUBLIC_API_URL=http://localhost:3001
EXPO_PUBLIC_APP_SCHEME=pisto
EXPO_IOS_BUNDLE_IDENTIFIER=com.example.pisto
EXPO_ANDROID_PACKAGE=com.example.pisto
`;

type Logger = Pick<Console, "log" | "error">;

type InitOptions = {
  dryRun?: boolean;
  logger?: Logger;
  root?: string;
};

type DiagnosticLevel = "PASS" | "WARN" | "FAIL";

type Diagnostic = {
  detail: string;
  level: DiagnosticLevel;
  name: string;
};

type DoctorOptions = {
  logger?: Logger;
  root?: string;
};

const HELP = `Pisto Stack local CLI

Usage:
  bun run scripts/pisto.ts <command> [options]

Commands:
  init       Create local environment files without overwriting existing files.
  doctor     Check Bun, Docker, repository configuration, and local environment files.
  help       Show this help.

Options:
  --dry-run  With init, report what would be created without writing files.
  -h, --help Show command help.

Safety:
  init only writes .env and apps/app/.env.local when they do not already exist.
  doctor is read-only. This CLI never starts services or changes external systems.
`;

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}

async function fileExists(path: string): Promise<boolean> {
  return Bun.file(path).exists();
}

function displayPath(root: string, path: string): string {
  return relative(root, path).replaceAll("\\", "/") || ".";
}

export function generateBetterAuthSecret(): string {
  return randomBytes(32).toString("base64url");
}

function looksLikePlaceholder(value: string): boolean {
  const normalized = value
    .trim()
    .replace(/^['"]|['"]$/g, "")
    .toLowerCase();
  return (
    normalized.length === 0 ||
    normalized.includes("change-me") ||
    normalized.includes("changeme") ||
    normalized.includes("replace-me") ||
    normalized.includes("generated_better_auth_secret") ||
    (normalized.startsWith("<") && normalized.endsWith(">"))
  );
}

export function injectBetterAuthSecret(template: string, secret: string): string {
  const normalized = template.endsWith("\n") ? template : `${template}\n`;
  const pattern = /^BETTER_AUTH_SECRET\s*=.*$/m;

  if (pattern.test(normalized)) {
    return normalized.replace(pattern, `BETTER_AUTH_SECRET=${secret}`);
  }

  return `${normalized}\nBETTER_AUTH_SECRET=${secret}\n`;
}

export async function createFileExclusive(
  path: string,
  contents: string,
): Promise<"created" | "exists"> {
  await mkdir(dirname(path), { recursive: true });

  try {
    const handle = await open(path, "wx", 0o600);
    try {
      await handle.writeFile(contents, "utf8");
    } finally {
      await handle.close();
    }
    return "created";
  } catch (error) {
    if (isNodeError(error) && error.code === "EEXIST") {
      return "exists";
    }
    throw error;
  }
}

async function loadTemplate(examplePath: string, fallback: string): Promise<string> {
  if (!(await fileExists(examplePath))) {
    return fallback;
  }
  return readFile(examplePath, "utf8");
}

export async function runInit(options: InitOptions = {}): Promise<number> {
  const root = resolve(options.root ?? PROJECT_ROOT);
  const logger = options.logger ?? console;
  const dryRun = options.dryRun ?? false;
  const secret = generateBetterAuthSecret();
  const targets = [
    {
      example: join(root, ".env.example"),
      fallback: SERVER_ENV_FALLBACK,
      path: join(root, ".env"),
      transform: (template: string) => injectBetterAuthSecret(template, secret),
    },
    {
      example: join(root, "apps", "app", ".env.example"),
      fallback: APP_ENV_FALLBACK,
      path: join(root, "apps", "app", ".env.local"),
      transform: (template: string) => template,
    },
  ];

  logger.log(dryRun ? "Pisto Stack initialization (dry run)" : "Pisto Stack initialization");

  let created = 0;
  let preserved = 0;

  for (const target of targets) {
    const shownPath = displayPath(root, target.path);
    if (await fileExists(target.path)) {
      logger.log(`PRESERVED  ${shownPath} (already exists)`);
      preserved += 1;
      continue;
    }

    if (dryRun) {
      logger.log(`WOULD CREATE  ${shownPath}`);
      continue;
    }

    const template = await loadTemplate(target.example, target.fallback);
    const result = await createFileExclusive(target.path, target.transform(template));
    if (result === "created") {
      logger.log(`CREATED    ${shownPath}`);
      created += 1;
    } else {
      logger.log(`PRESERVED  ${shownPath} (created by another process)`);
      preserved += 1;
    }
  }

  if (dryRun) {
    logger.log("No files were written.");
  } else {
    logger.log(`Finished: ${created} created, ${preserved} preserved.`);
    logger.log("Secret values were generated locally and were not printed.");
  }

  logger.log("Next: review the local env files, then run `bun run doctor`.");
  return 0;
}

export function parseEnv(contents: string): Map<string, string> {
  const values = new Map<string, string>();

  for (const originalLine of contents.split(/\r?\n/)) {
    const line = originalLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }

    const match = /^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/.exec(line);
    if (!match) {
      continue;
    }

    const [, key, rawValue] = match;
    let value = rawValue.trim();
    if (
      value.length >= 2 &&
      ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'")))
    ) {
      value = value.slice(1, -1);
    }
    values.set(key, value);
  }

  return values;
}

function parseVersion(version: string): [number, number, number] | null {
  const match = /^(\d+)\.(\d+)\.(\d+)/.exec(version.trim());
  if (!match) {
    return null;
  }
  return [Number(match[1]), Number(match[2]), Number(match[3])];
}

export function isVersionAtLeast(actual: string, minimum: string): boolean {
  const actualParts = parseVersion(actual);
  const minimumParts = parseVersion(minimum);
  if (!actualParts || !minimumParts) {
    return false;
  }

  for (let index = 0; index < actualParts.length; index += 1) {
    if (actualParts[index] > minimumParts[index]) {
      return true;
    }
    if (actualParts[index] < minimumParts[index]) {
      return false;
    }
  }
  return true;
}

function runReadOnlyCommand(command: string[]): { output: string; success: boolean } {
  try {
    const result = Bun.spawnSync({
      cmd: command,
      stderr: "pipe",
      stdout: "pipe",
      timeout: 8_000,
    });
    const stdout = result.stdout.toString().trim();
    const stderr = result.stderr.toString().trim();
    return {
      output: stdout || stderr,
      success: result.exitCode === 0,
    };
  } catch (error) {
    return {
      output: error instanceof Error ? error.message : "Command could not be executed.",
      success: false,
    };
  }
}

function addDiagnostic(
  diagnostics: Diagnostic[],
  level: DiagnosticLevel,
  name: string,
  detail: string,
): void {
  diagnostics.push({ detail, level, name });
}

async function readEnvIfPresent(path: string): Promise<Map<string, string>> {
  if (!(await fileExists(path))) {
    return new Map();
  }
  return parseEnv(await readFile(path, "utf8"));
}

function configuredValue(values: Map<string, string>, key: string): string {
  if (Object.hasOwn(process.env, key)) {
    return process.env[key]?.trim() ?? "";
  }
  return values.get(key)?.trim() ?? "";
}

type FeatureFlag = "enabled" | "disabled" | "invalid";

function parseFeatureFlag(value: string): FeatureFlag {
  const normalized = value.trim().toLowerCase();
  if (["1", "true", "yes", "on"].includes(normalized)) return "enabled";
  if (["", "0", "false", "no", "off"].includes(normalized)) return "disabled";
  return "invalid";
}

function inspectOptionalInteger(
  values: Map<string, string>,
  diagnostics: Diagnostic[],
  key: string,
  minimum: number,
  maximum: number,
): void {
  const value = configuredValue(values, key);
  if (!value) return;
  const parsed = Number(value);
  if (!Number.isSafeInteger(parsed) || parsed < minimum || parsed > maximum) {
    addDiagnostic(diagnostics, "FAIL", key, `Must be an integer from ${minimum} to ${maximum}.`);
  }
}

function inspectBoolean(
  values: Map<string, string>,
  diagnostics: Diagnostic[],
  key: string,
): FeatureFlag {
  const result = parseFeatureFlag(configuredValue(values, key));
  if (result === "invalid") {
    addDiagnostic(
      diagnostics,
      "FAIL",
      key,
      "Must be one of true, false, 1, 0, yes, no, on, or off.",
    );
  }
  return result;
}

function jsonValue(value: string): unknown | undefined {
  try {
    return JSON.parse(value);
  } catch {
    return undefined;
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function validEntitlementKey(value: unknown): value is string {
  return typeof value === "string" && /^[a-z0-9]+(?:[._-][a-z0-9]+)*$/.test(value);
}

function validPolarProducts(value: unknown): boolean {
  if (!Array.isArray(value) || value.length === 0) return false;
  const productIds = new Set<string>();
  const slugs = new Set<string>();
  const allowedKeys = new Set(["productId", "slug", "entitlementKey", "name", "description"]);

  for (const product of value) {
    if (!isRecord(product) || Object.keys(product).some((key) => !allowedKeys.has(key)))
      return false;
    const productId = product.productId;
    const slug = product.slug;
    const name = product.name;
    const description = product.description;
    if (
      typeof productId !== "string" ||
      !/^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(productId) ||
      typeof slug !== "string" ||
      !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug) ||
      !validEntitlementKey(product.entitlementKey) ||
      (name !== undefined && (typeof name !== "string" || name.length < 1 || name.length > 120)) ||
      (description !== undefined &&
        (typeof description !== "string" || description.length < 1 || description.length > 500)) ||
      productIds.has(productId) ||
      slugs.has(slug)
    ) {
      return false;
    }
    productIds.add(productId);
    slugs.add(slug);
  }
  return true;
}

function validEntitlementMap(value: unknown): boolean {
  return (
    isRecord(value) &&
    Object.keys(value).length > 0 &&
    Object.entries(value).every(([providerKey, entitlementKey]) => {
      return providerKey.length > 0 && validEntitlementKey(entitlementKey);
    })
  );
}

function isValidUrl(value: string, protocols = ["http:", "https:"]): boolean {
  try {
    const url = new URL(value);
    return protocols.includes(url.protocol) && Boolean(url.hostname);
  } catch {
    return false;
  }
}

function isReservedProductionHostname(hostname: string): boolean {
  const normalized = hostname
    .toLowerCase()
    .replace(/\.$/, "")
    .replace(/^\[|\]$/g, "");
  if (normalized === "localhost" || normalized === "::1" || normalized === "0.0.0.0") return true;
  if (/^127(?:\.\d{1,3}){3}$/.test(normalized)) return true;
  return [
    "localhost",
    "test",
    "invalid",
    "example",
    "example.com",
    "example.net",
    "example.org",
  ].some((suffix) => normalized === suffix || normalized.endsWith(`.${suffix}`));
}

function isValidConfiguredHttpUrl(value: string, production: boolean): boolean {
  try {
    const url = new URL(value);
    return (
      ["http:", "https:"].includes(url.protocol) &&
      (!production || url.protocol === "https:") &&
      !url.username &&
      !url.password &&
      (!production || !isReservedProductionHostname(url.hostname))
    );
  } catch {
    return false;
  }
}

function isExactHttpOrigin(value: string, requireHttps = false): boolean {
  try {
    const url = new URL(value);
    return (
      ["http:", "https:"].includes(url.protocol) &&
      (!requireHttps || url.protocol === "https:") &&
      url.origin === value
    );
  } catch {
    return false;
  }
}

function inspectOrigins(server: Map<string, string>, diagnostics: Diagnostic[]): void {
  const production = configuredValue(server, "NODE_ENV") === "production";
  const corsOrigins = configuredValue(server, "CORS_ORIGINS")
    .split(",")
    .map((value) => value.trim())
    .filter(Boolean);
  if (
    corsOrigins.some(
      (origin) =>
        !isExactHttpOrigin(origin, production) ||
        (production && isReservedProductionHostname(new URL(origin).hostname)),
    )
  ) {
    addDiagnostic(
      diagnostics,
      "FAIL",
      "CORS_ORIGINS",
      production
        ? "Production entries must be comma-separated exact HTTPS origins."
        : "Entries must be comma-separated exact HTTP(S) origins without paths.",
    );
  }

  const expoScheme = configuredValue(server, "EXPO_SCHEME").toLowerCase();
  const validScheme =
    !expoScheme ||
    (/^[a-z][a-z0-9+.-]*$/.test(expoScheme) &&
      !["http", "https", "javascript", "data", "file", "blob"].includes(expoScheme));
  if (!validScheme) {
    addDiagnostic(
      diagnostics,
      "FAIL",
      "EXPO_SCHEME",
      "Must be a valid private application URL scheme.",
    );
  }

  const trustedOrigins = configuredValue(server, "TRUSTED_ORIGINS")
    .split(",")
    .map((value) => value.trim())
    .filter(Boolean);
  const invalidTrustedOrigin = trustedOrigins.some((origin) => {
    if (/[*?]/.test(origin)) return true;
    if (/^https?:\/\//i.test(origin)) {
      return (
        !isExactHttpOrigin(origin, production) ||
        (production && isReservedProductionHostname(new URL(origin).hostname))
      );
    }
    const scheme = origin.match(/^([a-z][a-z0-9+.-]*):\/\/(?:[a-z0-9._~-]+)?$/i)?.[1];
    return !scheme || !expoScheme || scheme.toLowerCase() !== expoScheme;
  });
  if (invalidTrustedOrigin) {
    addDiagnostic(
      diagnostics,
      "FAIL",
      "TRUSTED_ORIGINS",
      production
        ? "Use exact HTTPS origins or the configured private app scheme; wildcards are invalid."
        : "Use exact HTTP(S) origins or the configured private app scheme; wildcards are invalid.",
    );
  }
}

async function inspectRepository(root: string, diagnostics: Diagnostic[]): Promise<void> {
  const requiredFiles = [
    "package.json",
    "bunfig.toml",
    "bun.lock",
    ".node-version",
    ".env.example",
    "compose.yaml",
    "apps/app/package.json",
    "apps/app/.env.example",
    "apps/api/package.json",
    "packages/contracts/package.json",
    "packages/db/package.json",
    "packages/auth/package.json",
    "packages/billing/package.json",
  ];

  const missing: string[] = [];
  for (const path of requiredFiles) {
    if (!(await fileExists(join(root, path)))) {
      missing.push(path);
    }
  }

  if (missing.length === 0) {
    addDiagnostic(
      diagnostics,
      "PASS",
      "Repository",
      "Required workspace configuration is present.",
    );
  } else {
    addDiagnostic(
      diagnostics,
      "FAIL",
      "Repository",
      `Missing required files: ${missing.join(", ")}.`,
    );
  }

  try {
    const packageJson = JSON.parse(await readFile(join(root, "package.json"), "utf8")) as {
      name?: string;
      packageManager?: string;
    };
    if (packageJson.name === "pisto-stack") {
      addDiagnostic(diagnostics, "PASS", "Workspace name", "package.json identifies pisto-stack.");
    } else {
      addDiagnostic(diagnostics, "FAIL", "Workspace name", "Expected package name pisto-stack.");
    }
    addDiagnostic(
      diagnostics,
      packageJson.packageManager === "bun@1.4.0" ? "PASS" : "FAIL",
      "Package manager pin",
      packageJson.packageManager === "bun@1.4.0"
        ? "package.json pins bun@1.4.0."
        : "Expected packageManager bun@1.4.0.",
    );
  } catch {
    addDiagnostic(
      diagnostics,
      "FAIL",
      "Workspace package",
      "package.json is missing or invalid JSON.",
    );
  }

  try {
    const bunfig = await readFile(join(root, "bunfig.toml"), "utf8");
    const hoistedLinker = /\[install\][\s\S]*?linker\s*=\s*["']hoisted["']/.test(bunfig);
    addDiagnostic(
      diagnostics,
      hoistedLinker ? "PASS" : "FAIL",
      "Bun linker",
      hoistedLinker
        ? "bunfig.toml selects the hoisted linker required by the Expo native dependency layout."
        : 'Expected [install] linker = "hoisted" in bunfig.toml for the Expo workspace.',
    );
  } catch {
    addDiagnostic(diagnostics, "FAIL", "Bun linker", "bunfig.toml could not be read.");
  }

  try {
    const authPackage = JSON.parse(
      await readFile(join(root, "packages", "auth", "package.json"), "utf8"),
    ) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    const lockfile = await readFile(join(root, "bun.lock"), "utf8");
    const aligned =
      authPackage.dependencies?.["better-auth"] === "1.7.1" &&
      authPackage.dependencies?.["@better-auth/expo"] === "1.7.1" &&
      authPackage.devDependencies?.auth === "1.7.1" &&
      /"auth":\s*\["auth@1\.7\.1"/.test(lockfile) &&
      !lockfile.includes("@better-auth/cli");
    addDiagnostic(
      diagnostics,
      aligned ? "PASS" : "FAIL",
      "Better Auth toolchain",
      aligned
        ? "better-auth, @better-auth/expo, and the auth CLI are aligned at 1.7.1."
        : "Expected better-auth, @better-auth/expo, and auth at 1.7.1 with no legacy @better-auth/cli lock entry.",
    );
  } catch {
    addDiagnostic(
      diagnostics,
      "FAIL",
      "Better Auth toolchain",
      "The auth manifest or lockfile could not be read.",
    );
  }

  try {
    const compose = await readFile(join(root, "compose.yaml"), "utf8");
    const expectedPostgres =
      /image:\s*postgres:18-alpine/.test(compose) &&
      /pisto_postgres_data:\/var\/lib\/postgresql(?:\s|$)/.test(compose);
    addDiagnostic(
      diagnostics,
      expectedPostgres ? "PASS" : "FAIL",
      "PostgreSQL Compose",
      expectedPostgres
        ? "PostgreSQL 18 uses the official 18+ /var/lib/postgresql volume target."
        : "Expected postgres:18-alpine with the named volume mounted at /var/lib/postgresql.",
    );
  } catch {
    addDiagnostic(diagnostics, "FAIL", "PostgreSQL Compose", "compose.yaml could not be read.");
  }
}

async function inspectEnvironment(root: string, diagnostics: Diagnostic[]): Promise<void> {
  const serverPath = join(root, ".env");
  const clientPath = join(root, "apps", "app", ".env.local");
  const server = await readEnvIfPresent(serverPath);
  const client = await readEnvIfPresent(clientPath);

  if (await fileExists(serverPath)) {
    addDiagnostic(diagnostics, "PASS", "Server environment", ".env exists.");
  } else {
    addDiagnostic(diagnostics, "WARN", "Server environment", "Run `bun run setup` to create .env.");
  }

  if (await fileExists(clientPath)) {
    addDiagnostic(diagnostics, "PASS", "App environment", "apps/app/.env.local exists.");
  } else {
    addDiagnostic(
      diagnostics,
      "WARN",
      "App environment",
      "Run `bun run setup` to create apps/app/.env.local.",
    );
  }

  const databaseUrl = configuredValue(server, "DATABASE_URL");
  if (!databaseUrl) {
    addDiagnostic(diagnostics, "WARN", "DATABASE_URL", "Not configured in the process or .env.");
  } else if (!isValidUrl(databaseUrl, ["postgres:", "postgresql:"])) {
    addDiagnostic(diagnostics, "FAIL", "DATABASE_URL", "Must be a valid PostgreSQL URL.");
  } else {
    addDiagnostic(diagnostics, "PASS", "DATABASE_URL", "A PostgreSQL URL is configured.");
  }

  inspectOptionalInteger(server, diagnostics, "PORT", 1, 65_535);
  inspectOptionalInteger(server, diagnostics, "API_PORT", 1, 65_535);
  inspectOptionalInteger(server, diagnostics, "API_REQUEST_BODY_LIMIT_BYTES", 1_024, 10_485_760);
  inspectOptionalInteger(server, diagnostics, "DATABASE_MAX_CONNECTIONS", 1, 100);
  inspectOptionalInteger(server, diagnostics, "DATABASE_CONNECT_TIMEOUT_SECONDS", 1, 60);
  inspectOptionalInteger(server, diagnostics, "DATABASE_IDLE_TIMEOUT_SECONDS", 1, 600);
  inspectOrigins(server, diagnostics);

  const authSecret = configuredValue(server, "BETTER_AUTH_SECRET");
  const versionedAuthSecrets = configuredValue(server, "BETTER_AUTH_SECRETS");
  if (!authSecret && !versionedAuthSecrets) {
    addDiagnostic(
      diagnostics,
      "WARN",
      "BETTER_AUTH_SECRET",
      "Not configured. Run `bun run setup` for a generated local secret.",
    );
  }

  if (authSecret && (authSecret.length < 32 || looksLikePlaceholder(authSecret))) {
    addDiagnostic(
      diagnostics,
      "FAIL",
      "BETTER_AUTH_SECRET",
      "Must contain at least 32 high-entropy characters and must not be a placeholder.",
    );
  } else if (authSecret) {
    addDiagnostic(
      diagnostics,
      "PASS",
      "BETTER_AUTH_SECRET",
      "A non-placeholder secret of sufficient length is configured.",
    );
  }

  if (versionedAuthSecrets) {
    const parsedSecrets = versionedAuthSecrets.split(",").map((entry) => {
      const separator = entry.indexOf(":");
      const version = Number(entry.slice(0, separator).trim());
      const value = separator >= 0 ? entry.slice(separator + 1).trim() : "";
      return { value, version };
    });
    const versions = parsedSecrets.map((entry) => entry.version);
    const valid =
      parsedSecrets.length > 0 &&
      parsedSecrets.every(
        (entry) =>
          Number.isSafeInteger(entry.version) &&
          entry.version > 0 &&
          entry.value.length >= 32 &&
          !looksLikePlaceholder(entry.value),
      ) &&
      new Set(versions).size === versions.length;
    addDiagnostic(
      diagnostics,
      valid ? "PASS" : "FAIL",
      "BETTER_AUTH_SECRETS",
      valid
        ? "A valid versioned secret set is configured."
        : "Use unique positive version:value entries whose values contain at least 32 characters.",
    );
  }

  const databaseSsl = configuredValue(server, "DATABASE_SSL");
  const allowedDatabaseSsl = ["disable", "prefer", "require", "verify-full"];
  if (!databaseSsl) {
    addDiagnostic(
      diagnostics,
      "WARN",
      "DATABASE_SSL",
      `Not configured; use one of ${allowedDatabaseSsl.join(", ")}.`,
    );
  } else if (!allowedDatabaseSsl.includes(databaseSsl)) {
    addDiagnostic(
      diagnostics,
      "FAIL",
      "DATABASE_SSL",
      `Must be one of ${allowedDatabaseSsl.join(", ")}; boolean values are invalid.`,
    );
  } else {
    addDiagnostic(diagnostics, "PASS", "DATABASE_SSL", `${databaseSsl} is valid.`);
  }

  const authUrl = configuredValue(server, "BETTER_AUTH_URL");
  if (!authUrl) {
    addDiagnostic(diagnostics, "WARN", "BETTER_AUTH_URL", "Not configured.");
  } else if (
    !isExactHttpOrigin(authUrl, configuredValue(server, "NODE_ENV") === "production") ||
    (configuredValue(server, "NODE_ENV") === "production" &&
      isReservedProductionHostname(new URL(authUrl).hostname))
  ) {
    addDiagnostic(
      diagnostics,
      "FAIL",
      "BETTER_AUTH_URL",
      configuredValue(server, "NODE_ENV") === "production"
        ? "Must be an exact HTTPS origin with a non-reserved hostname in production."
        : "Must be an exact HTTP(S) origin without a path or trailing slash.",
    );
  } else {
    addDiagnostic(diagnostics, "PASS", "BETTER_AUTH_URL", "An exact HTTP(S) origin is configured.");
  }

  inspectBoolean(server, diagnostics, "AUTH_EMAIL_PASSWORD_ENABLED");
  inspectBoolean(server, diagnostics, "AUTH_TRUSTED_PROXY_HEADERS");

  const apiUrl = configuredValue(client, "EXPO_PUBLIC_API_URL");
  const productionApp = configuredValue(client, "APP_VARIANT") === "production";
  if (!apiUrl) {
    addDiagnostic(diagnostics, "WARN", "EXPO_PUBLIC_API_URL", "Not configured.");
  } else if (
    !isExactHttpOrigin(apiUrl, productionApp) ||
    (productionApp && isReservedProductionHostname(new URL(apiUrl).hostname))
  ) {
    addDiagnostic(
      diagnostics,
      "FAIL",
      "EXPO_PUBLIC_API_URL",
      productionApp
        ? "Production app builds require an exact non-local HTTPS API origin."
        : "Must be an exact HTTP(S) origin without credentials, a path, query, or fragment.",
    );
  } else {
    addDiagnostic(
      diagnostics,
      "PASS",
      "EXPO_PUBLIC_API_URL",
      "An exact HTTP(S) origin is configured.",
    );
  }

  const clientScheme = configuredValue(client, "EXPO_PUBLIC_APP_SCHEME").toLowerCase();
  const serverScheme = configuredValue(server, "EXPO_SCHEME").toLowerCase();
  const validClientScheme =
    /^[a-z][a-z0-9+.-]*$/.test(clientScheme) &&
    !["http", "https", "javascript", "data", "file", "blob"].includes(clientScheme);
  if (!clientScheme) {
    addDiagnostic(diagnostics, "WARN", "EXPO_PUBLIC_APP_SCHEME", "Not configured.");
  } else if (!validClientScheme || (serverScheme && clientScheme !== serverScheme)) {
    addDiagnostic(
      diagnostics,
      "FAIL",
      "App scheme",
      "Use one valid private scheme and keep EXPO_PUBLIC_APP_SCHEME aligned with EXPO_SCHEME.",
    );
  } else {
    addDiagnostic(
      diagnostics,
      "PASS",
      "App scheme",
      "The public app scheme is valid and aligned with the server scheme.",
    );
  }

  const iosIdentifier = configuredValue(client, "EXPO_IOS_BUNDLE_IDENTIFIER");
  const androidPackage = configuredValue(client, "EXPO_ANDROID_PACKAGE");
  const validIdentifiers =
    /^[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)+$/.test(iosIdentifier) &&
    /^[A-Za-z][A-Za-z0-9_]*(?:\.[A-Za-z][A-Za-z0-9_]*)+$/.test(androidPackage);
  if (!iosIdentifier || !androidPackage) {
    addDiagnostic(
      diagnostics,
      productionApp ? "FAIL" : "WARN",
      "App identifiers",
      "Configure EXPO_IOS_BUNDLE_IDENTIFIER and EXPO_ANDROID_PACKAGE.",
    );
  } else if (
    !validIdentifiers ||
    (productionApp &&
      (iosIdentifier.startsWith("com.example.") || androidPackage.startsWith("com.example.")))
  ) {
    addDiagnostic(
      diagnostics,
      "FAIL",
      "App identifiers",
      productionApp
        ? "Production builds require valid non-example iOS and Android identifiers."
        : "App identifiers are not syntactically valid.",
    );
  } else {
    addDiagnostic(
      diagnostics,
      "PASS",
      "App identifiers",
      productionApp
        ? "Production iOS and Android identifiers are configured."
        : "iOS and Android identifiers are syntactically valid for local development.",
    );
  }

  const forbiddenClientKeys = [
    "BETTER_AUTH_SECRET",
    "BETTER_AUTH_SECRETS",
    "DATABASE_URL",
    "POSTGRES_PASSWORD",
    "POLAR_ACCESS_TOKEN",
    "POLAR_WEBHOOK_SECRET",
    "REVENUECAT_WEBHOOK_AUTHORIZATION",
    "REVENUECAT_WEBHOOK_SIGNING_SECRET",
    "GOOGLE_APPLICATION_CREDENTIALS",
    "EXPO_PUBLIC_POLAR_CHECKOUT_URL",
  ];
  const exposed = forbiddenClientKeys.filter((key) => client.has(key));
  const privateLike = [...client.keys()].filter(
    (key) => key.includes("PRIVATE_KEY") || key.includes("WEBHOOK_SECRET"),
  );
  const unsafeClientKeys = [...new Set([...exposed, ...privateLike])];
  if (unsafeClientKeys.length > 0) {
    addDiagnostic(
      diagnostics,
      "FAIL",
      "Client secrets",
      `Remove server-only variables from apps/app/.env.local: ${unsafeClientKeys.join(", ")}.`,
    );
  } else {
    addDiagnostic(diagnostics, "PASS", "Client secrets", "No known server-only keys were found.");
  }

  const billingState = inspectBoolean(server, diagnostics, "BILLING_ENABLED");
  if (billingState === "disabled") {
    addDiagnostic(
      diagnostics,
      "PASS",
      "Polar billing",
      "Disabled locally; no Polar credentials are required.",
    );
  } else if (billingState === "enabled") {
    const requiredPolar = [
      "POLAR_ACCESS_TOKEN",
      "POLAR_WEBHOOK_SECRET",
      "POLAR_PRODUCTS_JSON",
      "POLAR_SUCCESS_URL",
    ];
    const missingPolar = requiredPolar.filter((key) => !configuredValue(server, key));
    if (missingPolar.length > 0) {
      addDiagnostic(
        diagnostics,
        "FAIL",
        "Polar billing",
        `BILLING_ENABLED=true but these variables are missing: ${missingPolar.join(", ")}.`,
      );
    } else {
      const products = jsonValue(configuredValue(server, "POLAR_PRODUCTS_JSON"));
      const successUrl = configuredValue(server, "POLAR_SUCCESS_URL");
      const returnUrl = configuredValue(server, "POLAR_RETURN_URL");
      const polarServer = configuredValue(server, "POLAR_SERVER") || "sandbox";
      const polarTheme = configuredValue(server, "POLAR_THEME");
      const production = configuredValue(server, "NODE_ENV") === "production";
      const valid =
        validPolarProducts(products) &&
        isValidConfiguredHttpUrl(successUrl, production) &&
        (!returnUrl || isValidConfiguredHttpUrl(returnUrl, production)) &&
        ["sandbox", "production"].includes(polarServer) &&
        (!polarTheme || ["light", "dark"].includes(polarTheme)) &&
        !looksLikePlaceholder(configuredValue(server, "POLAR_ACCESS_TOKEN")) &&
        !looksLikePlaceholder(configuredValue(server, "POLAR_WEBHOOK_SECRET"));
      addDiagnostic(
        diagnostics,
        valid ? "PASS" : "FAIL",
        "Polar billing",
        valid
          ? "Required server-side Polar variables are configured."
          : "Check Polar credentials, product JSON, production HTTPS URLs, server, and theme values.",
      );
    }
  }

  const revenueCatState = inspectBoolean(server, diagnostics, "REVENUECAT_ENABLED");
  if (revenueCatState === "disabled") {
    addDiagnostic(
      diagnostics,
      "PASS",
      "RevenueCat webhooks",
      "Disabled locally; no RevenueCat webhook credentials are required.",
    );
  } else if (revenueCatState === "enabled") {
    const requiredRevenueCat = [
      "REVENUECAT_WEBHOOK_AUTHORIZATION",
      "REVENUECAT_ENTITLEMENT_MAP_JSON",
    ];
    const missingRevenueCat = requiredRevenueCat.filter((key) => !configuredValue(server, key));
    if (missingRevenueCat.length > 0) {
      addDiagnostic(
        diagnostics,
        "FAIL",
        "RevenueCat webhooks",
        `REVENUECAT_ENABLED=true but these variables are missing: ${missingRevenueCat.join(", ")}.`,
      );
    } else {
      const mapping = jsonValue(configuredValue(server, "REVENUECAT_ENTITLEMENT_MAP_JSON"));
      const validMapping = validEntitlementMap(mapping);
      const tolerance = configuredValue(server, "REVENUECAT_SIGNATURE_TOLERANCE_SECONDS") || "300";
      const parsedTolerance = Number(tolerance);
      const validTolerance =
        Number.isSafeInteger(parsedTolerance) && parsedTolerance >= 30 && parsedTolerance <= 3_600;
      const authorization = configuredValue(server, "REVENUECAT_WEBHOOK_AUTHORIZATION");
      const signingSecret = configuredValue(server, "REVENUECAT_WEBHOOK_SIGNING_SECRET");
      const validCredentials =
        !looksLikePlaceholder(authorization) &&
        (!signingSecret || !looksLikePlaceholder(signingSecret));
      addDiagnostic(
        diagnostics,
        validMapping && validTolerance && validCredentials ? "PASS" : "FAIL",
        "RevenueCat webhooks",
        validMapping && validTolerance && validCredentials
          ? "Required server-side RevenueCat variables are configured."
          : "Check webhook credentials, entitlement map JSON, and signature tolerance (30 to 3600 seconds).",
      );
    }
  }
}

export async function runDoctor(options: DoctorOptions = {}): Promise<number> {
  const root = resolve(options.root ?? PROJECT_ROOT);
  const logger = options.logger ?? console;
  const diagnostics: Diagnostic[] = [];

  if (isVersionAtLeast(Bun.version, MINIMUM_BUN_VERSION)) {
    addDiagnostic(diagnostics, "PASS", "Bun", `${Bun.version} satisfies >=${MINIMUM_BUN_VERSION}.`);
  } else {
    addDiagnostic(
      diagnostics,
      "FAIL",
      "Bun",
      `${Bun.version} is too old; install Bun >=${MINIMUM_BUN_VERSION}.`,
    );
  }

  const dockerVersion = runReadOnlyCommand(["docker", "--version"]);
  if (dockerVersion.success) {
    addDiagnostic(diagnostics, "PASS", "Docker CLI", dockerVersion.output);
  } else {
    addDiagnostic(
      diagnostics,
      "FAIL",
      "Docker CLI",
      "Docker is unavailable. Install Docker before local database development.",
    );
  }

  if (dockerVersion.success) {
    const composeConfig = runReadOnlyCommand([
      "docker",
      "compose",
      "--file",
      join(root, "compose.yaml"),
      "config",
      "--quiet",
    ]);
    addDiagnostic(
      diagnostics,
      composeConfig.success ? "PASS" : "FAIL",
      "Compose configuration",
      composeConfig.success
        ? "compose.yaml parses successfully."
        : `compose.yaml is invalid: ${composeConfig.output || "Docker Compose returned an error."}`,
    );

    const composeVersion = runReadOnlyCommand(["docker", "compose", "version"]);
    addDiagnostic(
      diagnostics,
      composeVersion.success ? "PASS" : "FAIL",
      "Docker Compose",
      composeVersion.success ? composeVersion.output : "The Docker Compose plugin is unavailable.",
    );

    const engine = runReadOnlyCommand(["docker", "info", "--format", "{{.ServerVersion}}"]);
    addDiagnostic(
      diagnostics,
      engine.success ? "PASS" : "WARN",
      "Docker engine",
      engine.success
        ? `Docker Engine ${engine.output} is reachable.`
        : "Docker is installed, but its engine is not reachable. Start Docker Desktop when needed.",
    );
  }

  const nodeVersion = runReadOnlyCommand(["node", "--version"]);
  const normalizedNodeVersion = nodeVersion.output.replace(/^v/, "");
  if (!nodeVersion.success) {
    addDiagnostic(
      diagnostics,
      "FAIL",
      "Node.js",
      `Node.js >=${MINIMUM_NODE_VERSION} is required by this repository (Expo SDK 57 requires >=${EXPO_MINIMUM_NODE_VERSION}).`,
    );
  } else if (
    !isVersionAtLeast(normalizedNodeVersion, MINIMUM_NODE_VERSION) ||
    isVersionAtLeast(normalizedNodeVersion, MAXIMUM_NODE_VERSION)
  ) {
    addDiagnostic(
      diagnostics,
      "FAIL",
      "Node.js",
      `${normalizedNodeVersion} is outside the supported >=${MINIMUM_NODE_VERSION} <${MAXIMUM_NODE_VERSION} range; use the repository pin.`,
    );
  } else {
    addDiagnostic(
      diagnostics,
      "PASS",
      "Node.js",
      `${normalizedNodeVersion} satisfies >=${MINIMUM_NODE_VERSION}.`,
    );
  }

  await inspectRepository(root, diagnostics);
  await inspectEnvironment(root, diagnostics);

  logger.log("Pisto Stack doctor");
  for (const item of diagnostics) {
    logger.log(`${item.level.padEnd(4)}  ${item.name}: ${item.detail}`);
  }

  const failures = diagnostics.filter((item) => item.level === "FAIL").length;
  const warnings = diagnostics.filter((item) => item.level === "WARN").length;
  logger.log(`Summary: ${failures} failure(s), ${warnings} warning(s).`);

  if (failures > 0) {
    logger.error("Doctor found blocking local configuration problems.");
    return 1;
  }

  logger.log("Doctor completed without blocking problems. No services were started.");
  return 0;
}

export async function main(
  argv = process.argv.slice(2),
  logger: Logger = console,
): Promise<number> {
  const [command = "help", ...flags] = argv;

  if (command === "help" || command === "--help" || command === "-h") {
    logger.log(HELP);
    return 0;
  }

  if (command === "init") {
    if (flags.includes("--help") || flags.includes("-h")) {
      logger.log(HELP);
      return 0;
    }
    const unknown = flags.filter((flag) => flag !== "--dry-run");
    if (unknown.length > 0) {
      logger.error(`Unknown init option: ${unknown.join(", ")}`);
      logger.log(HELP);
      return 2;
    }
    return runInit({ dryRun: flags.includes("--dry-run"), logger });
  }

  if (command === "doctor") {
    if (flags.includes("--help") || flags.includes("-h")) {
      logger.log(HELP);
      return 0;
    }
    if (flags.length > 0) {
      logger.error(`Unknown doctor option: ${flags.join(", ")}`);
      logger.log(HELP);
      return 2;
    }
    return runDoctor({ logger });
  }

  logger.error(`Unknown command: ${command}`);
  logger.log(HELP);
  return 2;
}

if (import.meta.main) {
  process.exitCode = await main();
}
