import type { InventoryMovementAction, ProductUnitKind } from "@pisto/contracts";
import type { TFunction } from "i18next";

import type { InventoryScreenCopy } from "../inventory/inventory-screen";
import type { MovementEditorCopy } from "../inventory/movement-editor";
import type { MovementHistoryCopy } from "../inventory/movement-history";
import type { ReversalEditorCopy } from "../inventory/reversal-editor";
import type { CatalogScreenCopy } from "./catalog-screen";
import type { CategoryManagerCopy } from "./category-manager";
import type { ProductDetailCopy } from "./product-detail";
import type { ProductEditorCopy } from "./product-editor";

export function productUnitLabels(t: TFunction): Record<ProductUnitKind, string> {
  return {
    gram: t("catalog.unitLabels.gram"),
    kilogram: t("catalog.unitLabels.kilogram"),
    liter: t("catalog.unitLabels.liter"),
    meter: t("catalog.unitLabels.meter"),
    milliliter: t("catalog.unitLabels.milliliter"),
    unit: t("catalog.unitLabels.unit"),
  };
}

export function inventoryMovementLabels(t: TFunction): Record<InventoryMovementAction, string> {
  return {
    adjust_in: t("inventory.movementActions.adjust_in"),
    adjust_out: t("inventory.movementActions.adjust_out"),
    receive: t("inventory.movementActions.receive"),
    reverse: t("inventory.movementActions.reverse"),
  };
}

export function catalogRemoteCopy(t: TFunction) {
  return {
    actionUnavailableDescription: t("catalog.remote.actionUnavailableDescription"),
    actionUnavailableTitle: t("catalog.remote.actionUnavailableTitle"),
    backToCatalog: t("catalog.remote.backToCatalog"),
    backToHistory: t("catalog.remote.backToHistory"),
    backToInventory: t("catalog.remote.backToInventory"),
    catalogReadOnly: t("catalog.remote.catalogReadOnly"),
    deniedDescription: t("catalog.remote.deniedDescription"),
    deniedTitle: t("catalog.remote.deniedTitle"),
    inventoryReadOnly: t("catalog.remote.inventoryReadOnly"),
    loadingBusiness: t("catalog.remote.loadingBusiness"),
    notFoundDescription: t("catalog.remote.notFoundDescription"),
    notFoundTitle: t("catalog.remote.notFoundTitle"),
    offlineDescription: t("remote.offlineDescription"),
    offlineTitle: t("remote.offlineTitle"),
    readOnlyTitle: t("catalog.remote.readOnlyTitle"),
    retry: t("common.retry"),
    stale: t("remote.stale"),
    unavailableDescription: t("catalog.remote.unavailableDescription"),
    unavailableTitle: t("catalog.remote.unavailableTitle"),
  };
}

export function buildCatalogCopy(t: TFunction) {
  const unitLabels = productUnitLabels(t);
  const movementActions = inventoryMovementLabels(t);
  const remote = catalogRemoteCopy(t);
  const uncertain = {
    retrySameConfirmation: t("common.retrySameConfirmation"),
    uncertainTitle: t("common.uncertainTitle"),
  };

  const list: CatalogScreenCopy = {
    allCategories: t("catalog.list.allCategories"),
    archived: t("catalog.list.archived"),
    categoriesLoading: t("catalog.list.categoriesLoading"),
    categoriesUnavailable: t("catalog.list.categoriesUnavailable"),
    createProduct: t("catalog.list.createProduct"),
    deniedDescription: t("catalog.list.deniedDescription"),
    deniedTitle: t("catalog.list.deniedTitle"),
    description: t("catalog.list.description"),
    emptyDescription: t("catalog.list.emptyDescription"),
    emptyTitle: t("catalog.list.emptyTitle"),
    errorDescription: t("catalog.list.errorDescription"),
    errorTitle: t("catalog.list.errorTitle"),
    eyebrow: t("catalog.list.eyebrow"),
    loadMore: t("catalog.list.loadMore"),
    loadMoreCategories: t("catalog.list.loadMoreCategories"),
    loading: t("catalog.list.loading"),
    loadingMore: t("catalog.list.loadingMore"),
    lowStock: t("catalog.list.lowStock"),
    manageCategories: t("catalog.list.manageCategories"),
    noPrice: t("catalog.list.noPrice"),
    noSku: t("catalog.list.noSku"),
    offlineDescription: remote.offlineDescription,
    offlineTitle: remote.offlineTitle,
    onHand: t("catalog.list.onHand"),
    openProduct: (name: string) => t("catalog.list.openProduct", { name }),
    readOnlyDescription: remote.catalogReadOnly,
    readOnlyTitle: remote.readOnlyTitle,
    retry: remote.retry,
    searchLabel: t("catalog.list.searchLabel"),
    searchPlaceholder: t("catalog.list.searchPlaceholder"),
    stale: remote.stale,
    statusLabel: t("catalog.list.statusLabel"),
    statuses: {
      active: t("catalog.list.statuses.active"),
      all: t("catalog.list.statuses.all"),
      archived: t("catalog.list.statuses.archived"),
    },
    stockNotTracked: t("catalog.list.stockNotTracked"),
    title: t("catalog.list.title"),
    unitLabels,
  };

  const categories: CategoryManagerCopy = {
    ...uncertain,
    active: t("catalog.categories.active"),
    archive: t("catalog.categories.archive"),
    archiveDescription: (name: string) => t("catalog.categories.archiveDescription", { name }),
    archiveTitle: t("catalog.categories.archiveTitle"),
    archived: t("catalog.categories.archived"),
    back: remote.backToCatalog,
    confirmArchive: t("catalog.categories.confirmArchive"),
    confirmCreate: t("catalog.categories.confirmCreate"),
    confirmUpdate: t("catalog.categories.confirmUpdate"),
    create: t("catalog.categories.create"),
    createTitle: t("catalog.categories.createTitle"),
    deniedDescription: t("catalog.categories.deniedDescription"),
    deniedTitle: t("catalog.categories.deniedTitle"),
    description: t("catalog.categories.description"),
    edit: t("catalog.categories.edit"),
    editTitle: t("catalog.categories.editTitle"),
    emptyDescription: t("catalog.categories.emptyDescription"),
    emptyTitle: t("catalog.categories.emptyTitle"),
    errorDescription: t("catalog.categories.errorDescription"),
    errorTitle: t("catalog.categories.errorTitle"),
    failedTitle: t("catalog.categories.failedTitle"),
    loadMore: t("catalog.categories.loadMore"),
    loading: t("catalog.categories.loading"),
    loadingMore: t("catalog.categories.loadingMore"),
    name: t("catalog.categories.name"),
    namePlaceholder: t("catalog.categories.namePlaceholder"),
    nameValidation: t("catalog.categories.nameValidation"),
    offlineDescription: remote.offlineDescription,
    offlineTitle: remote.offlineTitle,
    readOnlyDescription: remote.catalogReadOnly,
    readOnlyTitle: remote.readOnlyTitle,
    retry: remote.retry,
    review: t("catalog.categories.review"),
    reviewCreateDescription: t("catalog.categories.reviewCreateDescription"),
    reviewEditDescription: t("catalog.categories.reviewEditDescription"),
    reviewTitle: t("catalog.categories.reviewTitle"),
    searchLabel: t("catalog.categories.searchLabel"),
    searchPlaceholder: t("catalog.categories.searchPlaceholder"),
    stale: remote.stale,
    status: t("catalog.categories.status"),
    statuses: {
      active: t("catalog.categories.statuses.active"),
      all: t("catalog.categories.statuses.all"),
      archived: t("catalog.categories.statuses.archived"),
    },
    title: t("catalog.categories.title"),
    uncertainDescription: t("catalog.categories.uncertainDescription"),
  };

  const productEditor: ProductEditorCopy = {
    ...uncertain,
    archivedCategory: t("catalog.productEditor.archivedCategory"),
    back: remote.backToCatalog,
    categoriesUnavailable: t("catalog.productEditor.categoriesUnavailable"),
    category: t("catalog.productEditor.category"),
    confirmCreate: t("catalog.productEditor.confirmCreate"),
    confirmUpdate: t("catalog.productEditor.confirmUpdate"),
    createDescription: t("catalog.productEditor.createDescription"),
    createTitle: t("catalog.productEditor.createTitle"),
    disableTracking: t("catalog.productEditor.disableTracking"),
    edit: t("common.editData"),
    editDescription: t("catalog.productEditor.editDescription"),
    editTitle: t("catalog.productEditor.editTitle"),
    enableTracking: t("catalog.productEditor.enableTracking"),
    failedDescription: t("catalog.productEditor.failedDescription"),
    failedTitle: t("catalog.productEditor.failedTitle"),
    loadMoreCategories: t("catalog.productEditor.loadMoreCategories"),
    lowStockPlaceholder: t("catalog.productEditor.lowStockPlaceholder"),
    lowStockThreshold: t("catalog.productEditor.lowStockThreshold"),
    name: t("catalog.productEditor.name"),
    namePlaceholder: t("catalog.productEditor.namePlaceholder"),
    noCategory: t("catalog.productEditor.noCategory"),
    precision: t("catalog.productEditor.precision"),
    price: t("catalog.productEditor.price"),
    pricePlaceholder: t("catalog.productEditor.pricePlaceholder"),
    retryCategories: remote.retry,
    review: t("catalog.productEditor.review"),
    reviewDescription: t("catalog.productEditor.reviewDescription"),
    reviewTitle: t("catalog.productEditor.reviewTitle"),
    sku: t("catalog.productEditor.sku"),
    skuPlaceholder: t("catalog.productEditor.skuPlaceholder"),
    tracked: t("catalog.productEditor.tracked"),
    trackedDescription: t("catalog.productEditor.trackedDescription"),
    uncertainDescription: t("catalog.productEditor.uncertainDescription"),
    unit: t("catalog.productEditor.unit"),
    unitLabels,
  };

  const productEditorFields = {
    category: t("catalog.productEditor.reviewFields.category"),
    name: t("catalog.productEditor.reviewFields.name"),
    noPrice: t("catalog.productEditor.reviewFields.noPrice"),
    noSku: t("catalog.productEditor.reviewFields.noSku"),
    noThreshold: t("catalog.productEditor.reviewFields.noThreshold"),
    precision: t("catalog.productEditor.reviewFields.precision"),
    price: t("catalog.productEditor.reviewFields.price"),
    sku: t("catalog.productEditor.reviewFields.sku"),
    threshold: t("catalog.productEditor.reviewFields.threshold"),
    tracked: t("catalog.productEditor.reviewFields.tracked"),
    unit: t("catalog.productEditor.reviewFields.unit"),
  };

  const productDetail: ProductDetailCopy = {
    ...uncertain,
    active: t("catalog.productDetail.active"),
    archive: t("catalog.productDetail.archive"),
    archiveDescription: t("catalog.productDetail.archiveDescription"),
    archiveFailedDescription: t("catalog.productDetail.archiveFailedDescription"),
    archiveFailedTitle: t("catalog.productDetail.archiveFailedTitle"),
    archiveTitle: t("catalog.productDetail.archiveTitle"),
    archived: t("catalog.productDetail.archived"),
    back: remote.backToCatalog,
    cancel: t("common.cancel"),
    category: t("catalog.productDetail.category"),
    categoryUnavailable: t("catalog.productDetail.categoryUnavailable"),
    confirmArchive: t("catalog.productDetail.confirmArchive"),
    deniedDescription: t("catalog.productDetail.deniedDescription"),
    deniedTitle: t("catalog.productDetail.deniedTitle"),
    description: t("catalog.productDetail.description"),
    edit: t("catalog.productDetail.edit"),
    errorDescription: t("catalog.productDetail.errorDescription"),
    errorTitle: t("catalog.productDetail.errorTitle"),
    loading: t("catalog.productDetail.loading"),
    lowStockThreshold: t("catalog.productDetail.lowStockThreshold"),
    no: t("common.no"),
    noCategory: t("catalog.productDetail.noCategory"),
    noPrice: t("catalog.productDetail.noPrice"),
    noSku: t("catalog.productDetail.noSku"),
    noThreshold: t("catalog.productDetail.noThreshold"),
    notFoundDescription: remote.notFoundDescription,
    notFoundTitle: remote.notFoundTitle,
    notTracked: t("catalog.productDetail.notTracked"),
    offlineDescription: remote.offlineDescription,
    offlineTitle: remote.offlineTitle,
    onHand: t("catalog.productDetail.onHand"),
    precision: t("catalog.productDetail.precision"),
    price: t("catalog.productDetail.price"),
    readOnlyDescription: remote.catalogReadOnly,
    readOnlyTitle: remote.readOnlyTitle,
    retry: remote.retry,
    sku: t("catalog.productDetail.sku"),
    stale: remote.stale,
    status: t("catalog.productDetail.status"),
    title: t("catalog.productDetail.title"),
    tracked: t("catalog.productDetail.tracked"),
    uncertainDescription: t("catalog.productDetail.uncertainDescription"),
    unit: t("catalog.productDetail.unit"),
    unitLabels,
    yes: t("common.yes"),
  };

  const inventory: InventoryScreenCopy = {
    deniedDescription: t("inventory.list.deniedDescription"),
    deniedTitle: t("inventory.list.deniedTitle"),
    description: t("inventory.list.description"),
    emptyDescription: t("inventory.list.emptyDescription"),
    emptyTitle: t("inventory.list.emptyTitle"),
    errorDescription: t("inventory.list.errorDescription"),
    errorTitle: t("inventory.list.errorTitle"),
    eyebrow: t("inventory.list.eyebrow"),
    loadMore: t("inventory.list.loadMore"),
    loading: t("inventory.list.loading"),
    loadingMore: t("inventory.list.loadingMore"),
    lowStock: t("inventory.list.lowStock"),
    noThreshold: t("inventory.list.noThreshold"),
    offlineDescription: remote.offlineDescription,
    offlineTitle: remote.offlineTitle,
    onHand: t("inventory.list.onHand"),
    openHistory: (name: string) => t("inventory.list.openHistory", { name }),
    readOnlyDescription: remote.inventoryReadOnly,
    readOnlyTitle: remote.readOnlyTitle,
    retry: remote.retry,
    searchLabel: t("inventory.list.searchLabel"),
    searchPlaceholder: t("inventory.list.searchPlaceholder"),
    showAll: t("inventory.list.showAll"),
    showLowStock: t("inventory.list.showLowStock"),
    stale: remote.stale,
    threshold: t("inventory.list.threshold"),
    title: t("inventory.list.title"),
    unitLabels,
  };

  const movementHistory: MovementHistoryCopy = {
    actions: movementActions,
    addMovement: t("inventory.movementHistory.addMovement"),
    back: remote.backToInventory,
    deniedDescription: t("inventory.movementHistory.deniedDescription"),
    deniedTitle: t("inventory.movementHistory.deniedTitle"),
    description: t("inventory.movementHistory.description"),
    emptyDescription: t("inventory.movementHistory.emptyDescription"),
    emptyTitle: t("inventory.movementHistory.emptyTitle"),
    errorDescription: t("inventory.movementHistory.errorDescription"),
    errorTitle: t("inventory.movementHistory.errorTitle"),
    loadMore: t("inventory.movementHistory.loadMore"),
    loading: t("inventory.movementHistory.loading"),
    loadingMore: t("inventory.movementHistory.loadingMore"),
    lowStock: t("inventory.movementHistory.lowStock"),
    noThreshold: t("inventory.movementHistory.noThreshold"),
    occurrence: (date: string, time: string, timeZone: string) =>
      t("inventory.movementHistory.occurrence", { date, time, timeZone }),
    offlineDescription: remote.offlineDescription,
    offlineTitle: remote.offlineTitle,
    onHand: t("inventory.movementHistory.onHand"),
    readOnlyDescription: remote.inventoryReadOnly,
    readOnlyTitle: remote.readOnlyTitle,
    retry: remote.retry,
    reversed: t("inventory.movementHistory.reversed"),
    reverse: t("inventory.movementHistory.reverse"),
    reverses: t("inventory.movementHistory.reverses"),
    stale: remote.stale,
    threshold: t("inventory.movementHistory.threshold"),
    title: t("inventory.movementHistory.title"),
    unitLabels,
  };

  const movementEditor: MovementEditorCopy = {
    ...uncertain,
    actionLabel: t("inventory.movementEditor.actionLabel"),
    actions: {
      adjust_in: movementActions.adjust_in,
      adjust_out: movementActions.adjust_out,
      receive: movementActions.receive,
    },
    back: remote.backToHistory,
    confirm: t("inventory.movementEditor.confirm"),
    date: t("inventory.movementEditor.date"),
    datePlaceholder: t("inventory.movementEditor.datePlaceholder"),
    description: t("inventory.movementEditor.description"),
    edit: t("common.editData"),
    failedDescription: t("inventory.movementEditor.failedDescription"),
    failedTitle: t("inventory.movementEditor.failedTitle"),
    precisionHint: (precision: number) =>
      t("inventory.movementEditor.precisionHint", { count: precision }),
    quantity: t("inventory.movementEditor.quantity"),
    quantityPlaceholder: t("inventory.movementEditor.quantityPlaceholder"),
    reason: t("inventory.movementEditor.reason"),
    reasonPlaceholder: t("inventory.movementEditor.reasonPlaceholder"),
    review: t("inventory.movementEditor.review"),
    reviewDescription: t("inventory.movementEditor.reviewDescription"),
    reviewTitle: t("inventory.movementEditor.reviewTitle"),
    time: t("inventory.movementEditor.time"),
    timePlaceholder: t("inventory.movementEditor.timePlaceholder"),
    title: t("inventory.movementEditor.title"),
    uncertainDescription: t("inventory.movementEditor.uncertainDescription"),
  };

  const movementEditorFields = {
    action: t("inventory.movementEditor.reviewFields.action"),
    date: t("inventory.movementEditor.reviewFields.date"),
    quantity: t("inventory.movementEditor.reviewFields.quantity"),
    reason: t("inventory.movementEditor.reviewFields.reason"),
    time: t("inventory.movementEditor.reviewFields.time"),
    timeZone: t("inventory.movementEditor.reviewFields.timeZone"),
  };

  const reversal: ReversalEditorCopy = {
    ...uncertain,
    actions: movementActions,
    back: remote.backToHistory,
    cancel: t("common.editData"),
    confirm: t("inventory.reversal.confirm"),
    date: t("inventory.reversal.date"),
    datePlaceholder: t("inventory.reversal.datePlaceholder"),
    description: t("inventory.reversal.description"),
    failedDescription: t("inventory.reversal.failedDescription"),
    failedTitle: t("inventory.reversal.failedTitle"),
    movement: t("inventory.reversal.movement"),
    movementAction: t("inventory.reversal.movementAction"),
    originalDelta: t("inventory.reversal.originalDelta"),
    quantity: t("inventory.reversal.quantity"),
    reason: t("inventory.reversal.reason"),
    reasonPlaceholder: t("inventory.reversal.reasonPlaceholder"),
    reversalDelta: t("inventory.reversal.reversalDelta"),
    review: t("inventory.reversal.review"),
    reviewDescription: t("inventory.reversal.reviewDescription"),
    reviewTitle: t("inventory.reversal.reviewTitle"),
    time: t("inventory.reversal.time"),
    timePlaceholder: t("inventory.reversal.timePlaceholder"),
    timeZone: t("inventory.reversal.timeZone"),
    title: t("inventory.reversal.title"),
    uncertainDescription: t("inventory.reversal.uncertainDescription"),
  };

  return {
    categories,
    errorFallbacks: {
      archiveProduct: t("productErrors.contexts.archiveProduct.fallback"),
      category: t("productErrors.contexts.category.fallback"),
      movement: t("productErrors.contexts.movement.fallback"),
      product: t("productErrors.contexts.product.fallback"),
      reversal: t("productErrors.contexts.reversal.fallback"),
    },
    inventory,
    list,
    movementEditor,
    movementEditorFields,
    movementHistory,
    productDetail,
    productEditor,
    productEditorFields,
    productEditorValidation: {
      name: t("catalog.productEditor.validation.name"),
      noChanges: t("catalog.productEditor.validation.noChanges"),
      price: t("catalog.productEditor.validation.price"),
      sku: t("catalog.productEditor.validation.sku"),
      threshold: t("catalog.productEditor.validation.threshold"),
    },
    movementValidation: {
      date: t("inventory.movementEditor.validation.date"),
      quantity: t("inventory.movementEditor.validation.quantity"),
      reason: t("inventory.movementEditor.validation.reason"),
      time: t("inventory.movementEditor.validation.time"),
    },
    remote,
    reversal,
    reversalValidation: {
      date: t("inventory.reversal.validation.date"),
      reason: t("inventory.reversal.validation.reason"),
      time: t("inventory.reversal.validation.time"),
    },
    unitLabels,
  };
}

export type CatalogCopy = ReturnType<typeof buildCatalogCopy>;
