import type { InventoryMovementAction, ProductUnitKind } from "@pisto/contracts";

const unitLabels: Record<ProductUnitKind, string> = {
  unit: "unidad",
  kilogram: "kilogramo",
  gram: "gramo",
  liter: "litro",
  milliliter: "mililitro",
  meter: "metro",
};

const movementLabels: Record<InventoryMovementAction, string> = {
  receive: "Recepción",
  adjust_in: "Ajuste de entrada",
  adjust_out: "Ajuste de salida",
  reverse: "Reversión",
};

const remote = {
  loadingBusiness: "Comprobando el acceso a tu negocio…",
  offlineTitle: "Sin conexión",
  offlineDescription:
    "Conéctate a internet para consultar información actualizada. No mostramos registros inventados.",
  deniedTitle: "Acceso de solo consulta",
  deniedDescription:
    "Tu rol actual no permite completar esta acción. El servidor volverá a comprobar el permiso al confirmar.",
  unavailableTitle: "No pudimos abrir esta información",
  unavailableDescription:
    "No cambiamos ningún registro. Vuelve a intentar la consulta cuando tengas conexión.",
  actionUnavailableTitle: "Esta acción no está disponible",
  actionUnavailableDescription:
    "El estado actual del registro no permite completar esta acción. Consulta el detalle actualizado antes de decidir.",
  notFoundTitle: "No encontramos el registro",
  notFoundDescription:
    "Puede que el registro ya no exista en este negocio o que no tengas acceso a él.",
  retry: "Volver a intentar",
  backToCatalog: "Volver al catálogo",
  backToInventory: "Volver al inventario",
  businessRequired: "Selecciona o crea un negocio para continuar.",
  readOnlyTitle: "Acceso de consulta",
  catalogReadOnly:
    "Puedes buscar y revisar productos, pero tu rol no permite crear, editar ni archivar el catálogo.",
  inventoryReadOnly:
    "Puedes consultar existencias e historial, pero tu rol no permite registrar ni revertir movimientos.",
  stale: "Mostramos la última información disponible; todavía no pudimos actualizarla.",
};

export const catalogInventoryCopy = {
  locale: "es-SV",
  remote,
  common: {
    operate: "Operar",
    cancel: "Cancelar",
    edit: "Editar datos",
    loadMore: "Cargar más",
    loadingMore: "Cargando más…",
    yes: "Sí",
    no: "No",
    active: "Activo",
    archived: "Archivado",
    status: "Estado",
    identifier: "Identificador",
    localDate: "Fecha local",
    localTime: "Hora local",
    timeZone: "Zona horaria",
    reason: "Motivo",
  },
  errors: {
    unauthorized: "Tu sesión venció. Inicia sesión de nuevo.",
    category: {
      validation: "Revisa el nombre antes de continuar.",
      conflict: "Ya existe una categoría con ese nombre o la categoría ya no admite cambios.",
      notFound: "La categoría ya no está disponible en este negocio.",
      forbidden: "Tu rol actual no permite administrar categorías.",
      idempotency:
        "Esta clave de confirmación ya se usó con otros datos. Edita y vuelve a revisar la operación.",
      fallback: "No pudimos guardar la categoría. Ningún cambio se confirmó.",
    },
    product: {
      validation: "Revisa los datos del producto antes de continuar.",
      conflict:
        "El SKU ya existe o el historial del producto impide cambiar su precisión o seguimiento.",
      notFound: "El producto ya no está disponible en este negocio.",
      forbidden: "Tu rol actual no permite administrar productos.",
      idempotency:
        "Esta clave de confirmación ya se usó con otros datos. Edita y vuelve a revisar la operación.",
      fallback: "No pudimos guardar el producto. Ningún cambio se confirmó.",
    },
    archiveProduct: {
      validation: "La confirmación para archivar no es válida.",
      conflict: "El producto ya está archivado o su estado cambió antes de confirmar.",
      notFound: "El producto ya no está disponible en este negocio.",
      forbidden: "Tu rol actual no permite archivar productos.",
      idempotency:
        "Esta clave de confirmación ya se usó con otra operación. Abre de nuevo el producto.",
      fallback: "No pudimos archivar el producto. Su estado no se confirmó como cambiado.",
    },
    movement: {
      validation: "Revisa la cantidad, el motivo, la fecha y la hora antes de continuar.",
      conflict:
        "La existencia o el estado actual del producto ya no permite este movimiento. Actualiza el historial antes de decidir.",
      notFound: "El producto ya no está disponible en este negocio.",
      forbidden: "Tu rol actual no permite cambiar existencias.",
      idempotency:
        "Esta clave de confirmación ya se usó con otros datos. Edita y vuelve a revisar el movimiento.",
      fallback: "No pudimos confirmar el movimiento. La existencia no se muestra como modificada.",
    },
    reversal: {
      validation: "Revisa el motivo, la fecha y la hora antes de continuar.",
      conflict:
        "El movimiento ya fue revertido, no admite reversión o la reversión dejaría una existencia negativa.",
      notFound: "El movimiento ya no está disponible en este negocio.",
      forbidden: "Tu rol actual no permite revertir movimientos.",
      idempotency:
        "Esta clave de confirmación ya se usó con otros datos. Abre de nuevo el movimiento.",
      fallback: "No pudimos confirmar la reversión. La existencia no se muestra como modificada.",
    },
    connection:
      "No pudimos conectar con Pisto. Conservamos exactamente la misma confirmación para un reintento seguro.",
    businessRequired: remote.businessRequired,
  },
  catalog: {
    title: "Catálogo",
    description: "Busca productos, revisa sus precios y abre el registro que necesitas operar.",
    eyebrow: "Operar",
    createProduct: "Nuevo producto",
    manageCategories: "Administrar categorías",
    searchLabel: "Buscar productos",
    searchPlaceholder: "Nombre o SKU",
    allCategories: "Todas las categorías",
    statusLabel: "Estado del producto",
    statuses: {
      active: "Activos",
      archived: "Archivados",
      all: "Todos",
    },
    loading: "Consultando el catálogo…",
    offlineTitle: remote.offlineTitle,
    offlineDescription: remote.offlineDescription,
    deniedTitle: "No puedes consultar el catálogo",
    deniedDescription: "El servidor no autorizó la consulta para el negocio seleccionado.",
    errorTitle: "No pudimos consultar el catálogo",
    errorDescription: "No mostramos una lista vacía porque la consulta no terminó correctamente.",
    retry: remote.retry,
    stale: remote.stale,
    emptyTitle: "No encontramos productos",
    emptyDescription:
      "No hay productos que coincidan con la búsqueda y los filtros actuales. Puedes cambiar los filtros o crear uno nuevo si tienes permiso.",
    archived: "Archivado",
    noSku: "Sin SKU",
    noPrice: "Sin precio de venta",
    stockNotTracked: "Existencia no controlada",
    lowStock: "Existencia baja",
    onHand: "Existencia",
    loadMore: "Cargar más productos",
    loadingMore: "Cargando más productos…",
    loadMoreCategories: "Mostrar más categorías",
    categoriesLoading: "Cargando categorías…",
    categoriesUnavailable: "No pudimos cargar todas las categorías.",
    readOnlyTitle: remote.readOnlyTitle,
    readOnlyDescription: remote.catalogReadOnly,
    unitLabels,
    openProduct: (name: string) => `Abrir ${name}`,
  },
  categories: {
    back: "Volver al catálogo",
    title: "Categorías",
    description:
      "Organiza el catálogo sin borrar referencias históricas. Archivar no reactiva ni libera el mismo nombre en esta versión.",
    create: "Nueva categoría",
    searchLabel: "Buscar categorías",
    searchPlaceholder: "Nombre de la categoría",
    statuses: { active: "Activas", archived: "Archivadas", all: "Todas" },
    loading: "Consultando las categorías…",
    emptyTitle: "No encontramos categorías",
    emptyDescription: "No hay categorías que coincidan con la búsqueda y el filtro actuales.",
    errorTitle: "No pudimos consultar las categorías",
    errorDescription: "La consulta falló; no la presentamos como una lista vacía.",
    deniedTitle: "No puedes consultar las categorías",
    deniedDescription: "El servidor no autorizó esta consulta para el negocio seleccionado.",
    offlineTitle: remote.offlineTitle,
    offlineDescription: remote.offlineDescription,
    stale: remote.stale,
    retry: remote.retry,
    loadMore: "Cargar más categorías",
    loadingMore: "Cargando más categorías…",
    status: "Estado",
    active: "Activa",
    archived: "Archivada",
    edit: "Editar",
    archive: "Archivar",
    name: "Nombre",
    namePlaceholder: "Ej. Bebidas",
    nameValidation: "Escribe un nombre de 1 a 80 caracteres.",
    createTitle: "Nueva categoría",
    editTitle: "Editar categoría",
    reviewTitle: "Revisa la categoría",
    reviewCreateDescription: "Confirma el nombre antes de crear la categoría.",
    reviewEditDescription: "Confirma el nuevo nombre antes de actualizar la categoría.",
    review: "Revisar categoría",
    confirmCreate: "Confirmar y crear",
    confirmUpdate: "Confirmar cambio",
    archiveTitle: "Archivar categoría",
    archiveDescription: (name: string) =>
      `“${name}” dejará de estar disponible para productos nuevos. Los productos y referencias existentes se conservarán. No se puede reactivar en esta versión.`,
    confirmArchive: "Confirmar archivo",
    failedTitle: "No se guardó la categoría",
    uncertainTitle: "No sabemos si llegó la confirmación",
    uncertainDescription:
      "Reintenta exactamente la misma operación. Pisto conserva los datos y la clave para evitar duplicados.",
    resolveUncertain: "Reintentar la misma confirmación",
    readOnlyTitle: remote.readOnlyTitle,
    readOnlyDescription: remote.catalogReadOnly,
  },
  productEditor: {
    back: "Volver al catálogo",
    createTitle: "Nuevo producto",
    editTitle: "Editar producto",
    createDescription: "Define el producto y cómo se controlará su existencia.",
    editDescription:
      "Actualiza los datos del producto. La precisión y el seguimiento no pueden cambiar después del primer movimiento.",
    reviewTitle: "Revisa el producto",
    reviewDescription:
      "Confirma el precio, la unidad y el seguimiento antes de guardar el registro.",
    name: "Nombre",
    namePlaceholder: "Ej. Café molido",
    sku: "SKU (opcional)",
    skuPlaceholder: "Ej. CAFE-250",
    price: "Precio de venta (opcional)",
    pricePlaceholder: "0.00",
    category: "Categoría",
    noCategory: "Sin categoría",
    archivedCategory: "archivada",
    unit: "Unidad de medida",
    unitLabels,
    precision: "Decimales de cantidad",
    tracked: "Controlar existencia",
    trackedDescription:
      "Actívalo para registrar entradas, salidas y alertas de existencia baja en un historial auditable.",
    enableTracking: "Activar seguimiento",
    disableTracking: "Desactivar seguimiento",
    lowStockThreshold: "Umbral de existencia baja (opcional)",
    lowStockPlaceholder: "Ej. 5",
    review: "Revisar producto",
    edit: "Editar datos",
    confirmCreate: "Confirmar y crear",
    confirmUpdate: "Confirmar cambios",
    failedTitle: "No se guardó el producto",
    failedDescription: "Ningún cambio se confirmó. Revisa el problema antes de continuar.",
    uncertainTitle: "No sabemos si llegó la confirmación",
    uncertainDescription:
      "Reintenta exactamente el mismo producto. Pisto conserva los datos y la clave para evitar duplicados.",
    resolveUncertain: "Reintentar la misma confirmación",
    loadMoreCategories: "Mostrar más categorías",
    retryCategories: remote.retry,
    categoriesUnavailable:
      "No pudimos cargar las categorías. Vuelve a intentarlo antes de revisar.",
    reviewFields: {
      name: "Nombre",
      sku: "SKU",
      price: "Precio de venta",
      category: "Categoría",
      unit: "Unidad",
      precision: "Decimales de cantidad",
      tracked: "Control de existencia",
      threshold: "Umbral de existencia baja",
      noSku: "Sin SKU",
      noPrice: "Sin precio de venta",
      noThreshold: "Sin umbral",
    },
    validation: {
      name: "Escribe un nombre de 1 a 120 caracteres.",
      sku: "El SKU no puede superar 64 caracteres.",
      price: "Escribe un precio válido con los decimales permitidos por la moneda.",
      threshold: "Escribe una cantidad no negativa con la precisión seleccionada.",
      noChanges: "Cambia al menos un dato antes de revisar la actualización.",
    },
  },
  productDetail: {
    back: "Volver al catálogo",
    title: "Producto",
    description: "Este es el registro canónico y su existencia derivada del historial.",
    edit: "Editar producto",
    archive: "Archivar producto",
    status: "Estado",
    active: "Activo",
    archived: "Archivado",
    sku: "SKU",
    noSku: "Sin SKU",
    price: "Precio de venta",
    noPrice: "Sin precio de venta",
    unit: "Unidad",
    unitLabels,
    precision: "Decimales de cantidad",
    category: "Categoría",
    noCategory: "Sin categoría",
    categoryUnavailable: "Categoría no disponible",
    tracked: "Control de existencia",
    yes: "Sí",
    no: "No",
    notTracked: "No se controla",
    onHand: "Existencia actual",
    lowStockThreshold: "Umbral de existencia baja",
    noThreshold: "Sin umbral",
    loading: "Consultando el producto…",
    offlineTitle: remote.offlineTitle,
    offlineDescription: remote.offlineDescription,
    deniedTitle: "No puedes consultar este producto",
    deniedDescription: "El servidor no autorizó esta consulta para el negocio seleccionado.",
    notFoundTitle: remote.notFoundTitle,
    notFoundDescription: remote.notFoundDescription,
    errorTitle: "No pudimos consultar el producto",
    errorDescription: "No mostramos datos parciales como si fueran el registro actual.",
    retry: remote.retry,
    stale: remote.stale,
    archiveTitle: "Archivar este producto",
    archiveDescription:
      "Dejará de aparecer en las listas activas y no aceptará cambios ni movimientos nuevos. Su historial se conservará. No se puede reactivar en esta versión.",
    confirmArchive: "Confirmar archivo",
    cancel: "Cancelar",
    archiveFailedTitle: "No se archivó el producto",
    archiveFailedDescription:
      "El producto no se muestra como archivado porque no hubo confirmación.",
    uncertainTitle: "No sabemos si llegó la confirmación",
    uncertainDescription:
      "Reintenta exactamente el mismo archivo. Pisto conserva la clave para resolverlo sin duplicar la operación.",
    resolveUncertain: "Reintentar la misma confirmación",
    readOnlyTitle: remote.readOnlyTitle,
    readOnlyDescription: remote.catalogReadOnly,
  },
  inventory: {
    title: "Inventario",
    description:
      "Consulta la existencia derivada de movimientos y atiende productos bajo su umbral.",
    eyebrow: "Operar",
    searchLabel: "Buscar inventario",
    searchPlaceholder: "Nombre o SKU",
    showAll: "Todos",
    showLowStock: "Existencia baja",
    loading: "Calculando existencias…",
    offlineTitle: remote.offlineTitle,
    offlineDescription: remote.offlineDescription,
    deniedTitle: "No puedes consultar el inventario",
    deniedDescription: "El servidor no autorizó la consulta para el negocio seleccionado.",
    errorTitle: "No pudimos calcular las existencias",
    errorDescription: "La consulta falló; no mostramos cantidades en cero como reemplazo.",
    retry: remote.retry,
    stale: remote.stale,
    emptyTitle: "No encontramos productos con seguimiento",
    emptyDescription:
      "No hay productos que coincidan con la búsqueda y el filtro actuales. El catálogo controla cuáles productos llevan existencia.",
    lowStock: "Existencia baja",
    threshold: "Umbral",
    noThreshold: "Sin umbral",
    onHand: "Existencia actual",
    loadMore: "Cargar más productos",
    loadingMore: "Cargando más productos…",
    readOnlyTitle: remote.readOnlyTitle,
    readOnlyDescription: remote.inventoryReadOnly,
    unitLabels,
    openHistory: (name: string) => `Abrir el historial de ${name}`,
  },
  movementHistory: {
    back: "Volver al inventario",
    title: "Historial de existencias",
    description:
      "Cada cambio es un movimiento auditable; la existencia es la suma exacta del historial.",
    addMovement: "Registrar movimiento",
    onHand: "Existencia actual",
    lowStock: "Existencia baja",
    threshold: "Umbral",
    noThreshold: "Sin umbral",
    loading: "Consultando movimientos…",
    offlineTitle: remote.offlineTitle,
    offlineDescription: remote.offlineDescription,
    deniedTitle: "No puedes consultar este historial",
    deniedDescription: "El servidor no autorizó esta consulta para el negocio seleccionado.",
    errorTitle: "No pudimos consultar el historial",
    errorDescription: "La consulta falló; no la presentamos como un historial vacío.",
    retry: remote.retry,
    stale: remote.stale,
    emptyTitle: "Todavía no hay movimientos",
    emptyDescription: "La existencia es cero porque el historial confirmado está vacío.",
    actions: movementLabels,
    reversed: "Revertido",
    reverses: "Revierte el movimiento",
    reverse: "Revertir",
    loadMore: "Cargar más movimientos",
    loadingMore: "Cargando más movimientos…",
    readOnlyTitle: remote.readOnlyTitle,
    readOnlyDescription: remote.inventoryReadOnly,
    unitLabels,
    occurrence: (date: string, time: string, timeZone: string) =>
      `${date} a las ${time} · ${timeZone}`,
  },
  movementEditor: {
    back: "Volver al historial",
    title: "Registrar movimiento",
    description: "Escribe el cambio real de existencia y el momento en que ocurrió.",
    reviewTitle: "Revisa el movimiento",
    reviewDescription:
      "Confirma la dirección, la cantidad y el momento antes de cambiar la existencia.",
    actions: {
      receive: movementLabels.receive,
      adjust_in: movementLabels.adjust_in,
      adjust_out: movementLabels.adjust_out,
    },
    actionLabel: "Tipo de movimiento",
    quantity: "Cantidad",
    quantityPlaceholder: "Ej. 12.5",
    reason: "Motivo",
    reasonPlaceholder: "Ej. Recepción del proveedor",
    date: "Fecha local",
    datePlaceholder: "AAAA-MM-DD",
    time: "Hora local",
    timePlaceholder: "HH:MM",
    precisionHint: (precision: number) =>
      `Este producto acepta hasta ${precision} ${precision === 1 ? "decimal" : "decimales"}.`,
    review: "Revisar movimiento",
    edit: "Editar datos",
    confirm: "Confirmar movimiento",
    failedTitle: "No se registró el movimiento",
    failedDescription: "La existencia no se muestra como modificada porque no hubo confirmación.",
    uncertainTitle: "No sabemos si llegó la confirmación",
    uncertainDescription:
      "Reintenta exactamente el mismo movimiento. Pisto conserva la clave para evitar duplicados.",
    resolveUncertain: "Reintentar la misma confirmación",
    reviewFields: {
      action: "Movimiento",
      quantity: "Cantidad",
      reason: "Motivo",
      date: "Fecha local",
      time: "Hora local",
      timeZone: "Zona horaria",
    },
    validation: {
      quantity: "Escribe una cantidad positiva con la precisión permitida.",
      reason: "Escribe un motivo de 1 a 240 caracteres.",
      date: "Escribe una fecha real con el formato AAAA-MM-DD.",
      time: "Usa el formato HH:MM.",
    },
  },
  reversal: {
    back: "Volver al historial",
    title: "Revertir movimiento",
    description:
      "Una reversión agrega el movimiento contrario; no borra ni modifica el historial original.",
    reason: "Motivo de la reversión",
    reasonPlaceholder: "Ej. Recepción registrada por error",
    date: "Fecha local de la reversión",
    datePlaceholder: "AAAA-MM-DD",
    time: "Hora local de la reversión",
    timeZone: "Zona horaria",
    timePlaceholder: "HH:MM",
    review: "Revisar reversión",
    reviewTitle: "Revisa la reversión",
    reviewDescription:
      "Confirma el movimiento original y el momento de la reversión. Esta acción no se puede revertir otra vez.",
    movement: "Movimiento original",
    movementAction: "Acción original",
    originalDelta: "Cambio original",
    reversalDelta: "Cambio de la reversión",
    quantity: "Cantidad",
    confirm: "Confirmar reversión",
    cancel: "Editar datos",
    failedTitle: "No se confirmó la reversión",
    failedDescription: "La existencia no se muestra como modificada porque no hubo confirmación.",
    uncertainTitle: "No sabemos si llegó la confirmación",
    uncertainDescription:
      "Reintenta exactamente la misma reversión. Pisto conserva la clave para resolverla sin duplicados.",
    resolveUncertain: "Reintentar la misma confirmación",
    actions: movementLabels,
    validation: {
      reason: "Escribe un motivo de 1 a 240 caracteres.",
      date: "Escribe una fecha real con el formato AAAA-MM-DD.",
      time: "Usa el formato HH:MM.",
    },
  },
} as const;
